// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.type Dog
.type Person

.decl bites(x:Dog, y:Person)
bites("struppi", "josef").
bites("struppi", "maria").
bites("alfi", "karl").

.decl bad(x:Dog)
.output bad()
bad(Dog) :- bites(Dog, _Anybody).
