.TH SOUFFLE-CONFIG 1 2016-03-25

.SH NAME
.B souffle-config - short description of souffle-config
.SH SYNOPSIS
.B souffle-config
[
.I options
]
.I files
.SH DESCRIPTION
.B Long description of souffle-config
.SH OPTIONS
.TP
.B -h, --help
show a help page.
.TP

.SH EXAMPLES

.B souffle-config ...

.SH VERSION

1.0

.SH LICENSE

Copyright (c) 2013, 2015, Oracle and/or its affiliates.
All rights reserved.

.SH SEE ALSO
\fBg++\fP(1), \fBjava\fP(1)
