.TH SOUFFLE-CONFIG 1 2017-03-30

.SH NAME
.B souffle-config - short description of souffle-config
.SH SYNOPSIS
.B souffle-config
[
.I options
]
.I files
.SH DESCRIPTION
.B Long description of souffle-config
.SH OPTIONS
.TP
.B -h
show a help page.
.TP
.B -l
list the libraries needed to compile with souffle.
.TP

.SH VERSION

1.1

.SH LICENSE
Copyright (c) 2016 Oracle and/or its affiliates. All Rights reserved.

.SH SEE ALSO
\fBg++\fP(1), \fBjava\fP(1)
