.TH SOUFFLE-WAVE 1 2016-06-12
.SH NAME
.B souffle-wave
\- C preprocessor for souffle.
.SH SYNOPSIS
.B souffle-wave
[
.I options
]
.I files
.SH DESCRIPTION
a standard conformant C++ preprocessor based on the Boost.Wave library.
.SH BASIC OPTIONS
.TP
.B -h, --help
print out program usage
.TP
.B -v, --version
print the version number
.TP
.B --copyright
 print out the copyright statement
.TP
.B --config-file arg
 specify a config file (alternatively: @filepath)
.SH LICENSE
Copyright (c) 2001-2012 Hartmut Kaiser
All rights reserved.
.SH SEE ALSO
\fBcpp\fP(1), \fBsouffle\fP(1)
