.TH SOUFFLE 1 2017-03-30

.SH NAME
.B souffle
\- translator of declarative Datalog programs into the C++ language.
.SH SYNOPSIS
.B souffle
[
.I options
]
.I files
.SH DESCRIPTION
Souffle is used as a domain-specific language for static program analysis over
large code bases with millions of lines of code. Souffle aims to produce
high-performance C++ code that can be compiled with the native compiler on the
target machine.
.SH OPTIONS
.TP
.B -h, --help
show a help page
.TP
.B -v, --verbose
verbose output
.TP
.B -F\fI<DIR>\fP, --fact-dir=\fI<DIR>\fP
specify directory for fact files
.TP
.B -D\fI<DIR>\fP, --output-dir=\fI<DIR>\fP
Specify directory for output relations (if \fI<DIR>\fP is -, all output is written to stdout)
.TP
.B -j\fI<N>\fP, --jobs=\fI<N>\fP
run interpreter/compiler in parallel using N threads, N=auto for system default
.TP
.B -c, --compile
compile datalog (translating to C++)
.TP
.B --auto-schedule
switch on automated clause scheduling for compiler
.TP
.B -o \fI<FILE>\fP, --dl-program=\fI<FILE>\fP
write executable program to \fI<FILE>\fP (without executing it)
.TP
.B -p\fI<FILE>\fP, --profile=\fI<FILE>\fP
enable profiling and write profile data to \fI<FILE>\fP
.TP
.B -d, --debug
enable debug mode
.TP
.B --debug-report=\fI<FILE>\fP
write debugging output to HTML report
.SH EXAMPLES
souffle program.dl
.SH VERSION
1.1
.SH LICENSE
Copyright (c) 2016 Oracle and/or its affiliates. All Rights reserved.
.SH SEE ALSO
\fBg++\fP(1), \fBjava\fP(1)
