//
// Record Type
//
// This test checks that record types are handled correctly.
// It was created for issue #238 "Segfault: Type checker fails to detect single negative numbers if record type is expected".
//

.type record = [ X:number, Y:number ]

.decl MyRelation( X:record )

// No Error
MyRelation(nil).
MyRelation([7, 7]).
MyRelation([-7, -7]).

// Error
MyRelation(0).
MyRelation(7).
MyRelation(-7).
MyRelation("7").
MyRelation(7, 7).
MyRelation(-7, -7).
MyRelation([7]).
MyRelation([7, 7, 7]).

.decl YourRelation( X:number ) output

YourRelation(x) :- MyRelation([x, _]).
