//
// Negative Numbers
//
// This test checks that negative numbers and minus signs are handled correctly.
// It was created for issue #276 "Souffle interpreter cannot ingest -2^31".
//

.decl expr(x:number) output

// First Expression

// no spaces
expr(-2^31).

// one space
expr(- 2^31).
expr(-2 ^31).
expr(-2^ 31).

// two spaces
expr(- 2 ^31).
expr(-2 ^ 31).
expr(- 2^ 31).

// three spaces
expr(- 2 ^ 31).

// Second Expression

// no spaces
expr(-(2^31)).

// one space
expr(- (2^31)).
expr(-(2 ^31)).
expr(-(2^ 31)).

// two spaces
expr(- (2 ^31)).
expr(-(2 ^ 31)).
expr(- (2^ 31)).

// three spaces
expr(- (2 ^ 31)).

// Third Expression

// no spaces
expr(-2147483648).
