//
// Negative Numbers
//
// This test checks that negative numbers and minus signs are handled correctly.
//

.decl expr(x:number) output

// First Expression

// no spaces
expr((-2^31) - 1).

// one space
expr((- 2^31) - 1).
expr((-2 ^31) - 1).
expr((-2^ 31) - 1).

// two spaces
expr((- 2 ^31) - 1).
expr((-2 ^ 31) - 1).
expr((- 2^ 31) - 1).

// three spaces
expr((- 2 ^ 31) - 1).

// Second Expression

// no spaces
expr(-(2^31) - 1).

// one space
expr(- (2^31) - 1).
expr(-(2 ^31) - 1).
expr(-(2^ 31) - 1).

// two spaces
expr(- (2 ^31) - 1).
expr(-(2 ^ 31) - 1).
expr(- (2^ 31) - 1).

// three spaces
expr(- (2 ^ 31) - 1).

// Third Expression

// no spaces
expr(-2147483647).

// one space
expr(- 2147483647).
