// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

//
// Name Clash
//
// This test is used to ensure that name clashes between identifiers do not occur in the generated code,
// in response to issue #226 (see https://github.com/souffle-lang/souffle/issues/226).
//

.comp MyComponent {
	.decl value(X:number)
}

.init boolean = MyComponent

.decl boolean_value(X:number)
.output boolean_value()

boolean_value(X) :- boolean.value(X).

boolean.value(1).

