// Souffle - A Datalog Compiler
// Copyright (c) 2016, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test allowed range of hexadecimal integers
.decl Hexadecimal (n:number)
.output Hexadecimal

Hexadecimal(0x00000000).
Hexadecimal(0xFFFFFFFF).
