// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test that the output string syntax is detected and parsed without error
.decl A(x:number)

.input A(IO="file",filename="../../syntactic/NameFromInputDec.facts",delimiter="g")

.decl B(x:number)
.output B()
.output B(IO="file",filename="NameFromOutputDec.csv",delimiter="g")
B(x) :- A(x).
