#!/bin/bash
#
# Copyright (c) 2015, Oracle and/or its affiliates.
#
# All rights reserved.
#

#
# script that compiles a generated C++ program and executes it
#
HEADER_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
if [ -f $HEADER_DIR/souffleprof.jar ]
then
   java -jar $HEADER_DIR/souffleprof.jar "$@"
else 
   echo "error: souffleprof.jar file is not installed in directory $HEADER_DIR" 1>&2
   exit 1
fi
