// Souffle - A Datalog Compiler
// Copyright (c) 2017, The Souffle Developers. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

// Test that the output string syntax is detected and parsed, and the results used without error
.decl A(x:number,y:number)

.input A(IO="file",filename="NameFromInputDec.facts",delimiter="g")

// Without output qualifier
.decl B(x:number,y:number)
.output B(IO="file",filename="NameFromOutputDec.csv",delimiter="h")
B(x,y) :- A(x,y).
