//
// Souffle - A Datalog Compiler
// Copyright (c) 2015 Oracle and/or its affiliates. All rights reserved
// Licensed under the Universal Permissive License v 1.0 as shown at:
// - https://opensource.org/licenses/UPL
// - <souffle root>/licenses/SOUFFLE-UPL.txt

.decl rel(reallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting: number, n2: number)
.printsize rel

rel(0, 1).
rel(0, 2).
rel(1, 2).

rel(thisIsAnotherreallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting, m) :-
  rel(thisIsAnotherreallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting, _ ),
  rel(m, _),
  thisIsAnotherreallyLongAttributeNameWhichCanBecomeUnreadbleVeryQuicklyButIsNeededForTesting < m.

