/*
* Souffle - A Datalog Compiler
* Copyright (c) 2016, The Souffle Developers. All rights reserved
* Licensed under the Universal Permissive License v 1.0 as shown at:
* - https://opensource.org/licenses/UPL
* - <souffle root>/licenses/SOUFFLE-UPL.txt
*/

#pragma once

#include <string>
#include <iostream>


class html_string {
public:
    inline std::string get_first_half() {
        return "<!DOCTYPE html><html lang=\"en\"><head> <meta charset=\"UTF-8\"> <title>Souffle Profiler</title></head><style>.rulesofrel,.tabcontent{-webkit-animation: fadeEffect 1s}a,abbr,acronym,address,applet,article,aside,audio,b,big,blockquote,body,canvas,caption,center,cite,code,dd,del,details,dfn,dl,dt,em,embed,fieldset,figcaption,figure,footer,form,h1,h2,h3,h4,h5,h6,header,html,i,iframe,img,ins,kbd,label,legend,li,mark,menu,nav,object,ol,output,p,pre,q,ruby,s,samp,section,small,span,strike,strong,sub,summary,sup,table,tbody,td,tfoot,th,thead,time,tr,tt,u,ul,var,video{margin: 0; padding: 0; border: 0; font: inherit; vertical-align: baseline}body,h1{font-size: 13px}article,aside,details,figcaption,figure,footer,header,hgroup,menu,nav,section{display: block}body,html{line-height: 1}ol,ul{list-style: none}blockquote,q{quotes: none}blockquote:after,blockquote:before,q:after,q:before{content: none}:focus{outline: 0}*,:after,:before{box-sizing: border-box}body{margin: 0; font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; line-height: 18px; color: #303030; background-color: #fafafa; -webkit-font-smoothing: antialiased; padding: 0}h1,h2,h3,h4,h5{font-weight: 700; display: block; margin: 0 0 10px}h1,ul{margin: 0 0 20px}h1{display: block; font-weight: 400; text-shadow: 0 1px 0 #fff}a,strong,table th{font-weight: 700}h1 span.description{color: #6d6d6d}h2{font-size: 18px; line-height: 24px; margin: 20px 0 10px}h3{font-size: 15px; margin: 20px 0}li{margin-left: 30px; margin-bottom: 3px}ul li{list-style: disc}ol li{list-style: decimal}a{color: #404040; text-decoration: none; border-bottom: 1px solid #ddd}a:hover{border-color: #d0d0d0}.notice{background: #ffa; border: 1px solid #cc7; display: block; padding: 10px; margin-bottom: 10px}.stretch{display: block; width: 100%}.pad1y{padding: 10px 0}.center{text-align: center}.content{margin-top: 40px; padding: 0 0 20px}table{background: #fff; max-width: 100%; border-spacing: 0; width: 100%; margin: 10px 0; border: 1px solid #ddd; border-collapse: separate; -webkit-box-shadow: 0 0 4px rgba(0, 0, 0, .1); -moz-box-shadow: 0 0 4px rgba(0, 0, 0, .1); box-shadow: 0 0 4px rgba(0, 0, 0, .1)}table td,table th{padding: 4px; line-height: 14px; text-align: left; border-top: 1px solid #ddd}.limiter,header{margin: 0 auto; padding: 0 20px}table th{background: #eee; background: -webkit-gradient(linear, left top, left bottom, from(#f6f6f6), to(#eee)); background: -moz-linear-gradient(top, #f6f6f6, #eee); text-shadow: 0 1px 0 #fff; vertical-align: bottom}table td{vertical-align: top}table tr{background: rgba(0, 255, 0, 0)}table tbody:first-child tr:first-child td,table tbody:first-child tr:first-child th,table thead:first-child tr td,table thead:first-child tr th,table thead:first-child tr:first-child th{border-top: 0}table tbody+tbody{border-top: 2px solid #ddd}table td+td,table td+th,table th+td,table th+th{border-left: 1px solid #ddd}header{width: 960px}.limiter{width: 520px}.links{width: 480px; margin: 50px auto 0}.links a{width: 50%; float: left}a.button{background: #1F90FF; border: 1px solid #1f4fff; height: 40px; line-height: 38px; color: #fff; display: inline-block; text-align: center; padding: 0 10px; -webkit-border-radius: 1px; border-radius: 1px; -webkit-transition: box-shadow 150ms linear; -moz-transition: box-shadow 150ms linear; -o-transition: box-shadow 150ms linear; transition: box-shadow 150ms linear}pre,pre code{line-height: 1.25em}a.button:hover{background-color: #0081ff; -webkit-box-shadow: 0 1px 5px rgba(0, 0, 0, .25); box-shadow: 0 1px 5px rgba(0, 0, 0, .25); border: 1px solid #1f4fff}a.button:active,a.button:focus{background: #0081ff; -webkit-box-shadow: inset 0 1px 5px rgba(0, 0, 0, .25); box-shadow: inset 0 1px 5px rgba(0, 0, 0, .25)}.options{margin: 10px 0 30px 15px}.options h3{display: block; padding-top: 10px; margin-top: 20px}.options h3:first-child{border: none; margin-top: 0}code,pre{font-family: Consolas, Menlo, 'Liberation Mono', Courier, monospace; word-wrap: break-word; color: #333}pre{font-size: 13px; background: #fff; padding: 10px 15px; margin: 10px 0; overflow: auto; -webkit-box-shadow: 0 1px 3px rgba(0, 0, 0, .3); box-shadow: 0 1px 3px rgba(0, 0, 0, .3)}code{font-size: 12px; border: 0; padding: 0; background: #e6e6e6; background: rgba(0, 0, 0, .08); box-shadow: 0 0 0 2px rgba(0, 0, 0, .08)}pre code{font-size: 13px; background: 0 0; box-shadow: none; border: none; padding: 0; margin: 0}.col12{width: 100%}.col6{width: 50%; float: left; display: block}#toolbar-button,ul.tab li a{display: inline-block; text-align: center; text-decoration: none}.pill-group{margin: 40px 0 0}.pill-group a:first-child{border-radius: 20px 0 0 20px; border-right-width: 0}.pill-group a:last-child{border-radius: 0 20px 20px 0}#toolbar-button{background-color: #4CAF50; border: none; color: #fff; margin: 7px 12px; padding: 8px 14px; font-size: 32px}.tabcontent,ul.tab{border: 1px solid #ccc}#toolbar-button:hover{background-color: #0081ff; -webkit-box-shadow: 0 1px 5px rgba(0, 0, 0, .25); box-shadow: 0 1px 5px rgba(0, 0, 0, .25)}#toolbar-button:active,#toolbar-button:focus{background: #0081ff; -webkit-box-shadow: inset 0 1px 5px rgba(0, 0, 0, .25); box-shadow: inset 0 1px 5px rgba(0, 0, 0, .25)}ul.tab{margin: 0; padding: 0; overflow: hidden; background-color: #f1f1f1}ul.tab li{float: left; list-style: none}ul.tab li a{color: #000; padding: 14px 16px; transition: .3s; font-size: 17px}ul.tab li a:hover{background-color: #ddd}.active,ul.tab li a:focus{background-color: #ccc}.tabcontent{display: none; padding: 6px 12px; border-top: none; animation: fadeEffect 1s}.rulesofrel{display: none; animation: fadeEffect 1s}.RulVerTable{display: none; -webkit-animation: fadeEffect 1s; animation: fadeEffect 1s}@-webkit-keyframes fadeEffect{from{opacity: 0}to{opacity: 1}}@keyframes fadeEffect{from{opacity: 0}to{opacity: 1}}.perc_time,.perc_tup{padding: 0; margin: 0; background: #aaf; width: 100%; height: 30px; font: inherit; font-weight: 700; color: #000}p{padding: 4px}th[role=columnheader]:not(.no-sort){cursor: pointer}th[role=columnheader]:not(.no-sort):after{content: ''; float: right; margin-top: 7px; border-width: 0 4px 4px; border-style: solid; border-color: #404040 transparent; visibility: hidden; opacity: 0; -webkit-user-select: none; -moz-user-select: none; user-select: none}.ct-double-octave:before,.ct-major-eleventh:before,.ct-major-second:before,.ct-major-seventh:before,.ct-major-sixth:before,.ct-major-tenth:before,.ct-major-third:before,.ct-major-twelfth:before,.ct-minor-second:before,.ct-minor-seventh:before,.ct-minor-sixth:before,.ct-minor-third:before,.ct-octave:before,.ct-perfect-fifth:before,.ct-perfect-fourth:before,.ct-square:before{float: left; content: \"\"; height: 0}th[aria-sort=ascending]:not(.no-sort):after{border-bottom: none; border-width: 4px 4px 0}th[aria-sort]:not(.no-sort):after{visibility: visible; opacity: .4}th[role=columnheader]:not(.no-sort):hover:after{visibility: visible; opacity: 1}.ct-double-octave:after,.ct-major-eleventh:after,.ct-major-second:after,.ct-major-seventh:after,.ct-major-sixth:after,.ct-major-tenth:after,.ct-major-third:after,.ct-major-twelfth:after,.ct-minor-second:after,.ct-minor-seventh:after,.ct-minor-sixth:after,.ct-minor-third:after,.ct-octave:after,.ct-perfect-fifth:after,.ct-perfect-fourth:after,.ct-square:after{content: \"\"; clear: both}.ct-label{fill: rgba(0, 0, 0, .4); color: rgba(0, 0, 0, .4); font-size: .75rem; line-height: 1}.ct-grid-background,.ct-line{fill: none}.ct-chart-bar .ct-label,.ct-chart-line .ct-label{display: block; display: -webkit-box; display: -moz-box; display: -ms-flexbox; display: -webkit-flex; display: flex}.ct-chart-donut .ct-label,.ct-chart-pie .ct-label{dominant-baseline: central}.ct-label.ct-horizontal.ct-start{-webkit-box-align: flex-end; -webkit-align-items: flex-end; -ms-flex-align: flex-end; align-items: flex-end; -webkit-box-pack: flex-start; -webkit-justify-content: flex-start; -ms-flex-pack: flex-start; justify-content: flex-start; text-align: left; text-anchor: start}.ct-label.ct-horizontal.ct-end{-webkit-box-align: flex-start; -webkit-align-items: flex-start; -ms-flex-align: flex-start; align-items: flex-start; -webkit-box-pack: flex-start; -webkit-justify-content: flex-start; -ms-flex-pack: flex-start; justify-content: flex-start; text-align: left; text-anchor: start}.ct-label.ct-vertical.ct-start{-webkit-box-align: flex-end; -webkit-align-items: flex-end; -ms-flex-align: flex-end; align-items: flex-end; -webkit-box-pack: flex-end; -webkit-justify-content: flex-end; -ms-flex-pack: flex-end; justify-content: flex-end; text-align: right; text-anchor: end}.ct-label.ct-vertical.ct-end{-webkit-box-align: flex-end; -webkit-align-items: flex-end; -ms-flex-align: flex-end; align-items: flex-end; -webkit-box-pack: flex-start; -webkit-justify-content: flex-start; -ms-flex-pack: flex-start; justify-content: flex-start; text-align: left; text-anchor: start}.ct-chart-bar .ct-label.ct-horizontal.ct-start{-webkit-box-align: flex-end; -webkit-align-items: flex-end; -ms-flex-align: flex-end; align-items: flex-end; -webkit-box-pack: center; -webkit-justify-content: center; -ms-flex-pack: center; justify-content: center; text-align: center; text-anchor: start}.ct-chart-bar .ct-label.ct-horizontal.ct-end{-webkit-box-align: flex-start; -webkit-align-items: flex-start; -ms-flex-align: flex-start; align-items: flex-start; -webkit-box-pack: center; -webkit-justify-content: center; -ms-flex-pack: center; justify-content: center; text-align: center; text-anchor: start}.ct-chart-bar.ct-horizontal-bars .ct-label.ct-horizontal.ct-start{-webkit-box-align: flex-end; -webkit-align-items: flex-end; -ms-flex-align: flex-end; align-items: flex-end; -webkit-box-pack: flex-start; -webkit-justify-content: flex-start; -ms-flex-pack: flex-start; justify-content: flex-start; text-align: left; text-anchor: start}.ct-chart-bar.ct-horizontal-bars .ct-label.ct-horizontal.ct-end{-webkit-box-align: flex-start; -webkit-align-items: flex-start; -ms-flex-align: flex-start; align-items: flex-start; -webkit-box-pack: flex-start; -webkit-justify-content: flex-start; -ms-flex-pack: flex-start; justify-content: flex-start; text-align: left; text-anchor: start}.ct-chart-bar.ct-horizontal-bars .ct-label.ct-vertical.ct-start{-webkit-box-align: center; -webkit-align-items: center; -ms-flex-align: center; align-items: center; -webkit-box-pack: flex-end; -webkit-justify-content: flex-end; -ms-flex-pack: flex-end; justify-content: flex-end; text-align: right; text-anchor: end}.ct-chart-bar.ct-horizontal-bars .ct-label.ct-vertical.ct-end{-webkit-box-align: center; -webkit-align-items: center; -ms-flex-align: center; align-items: center; -webkit-box-pack: flex-start; -webkit-justify-content: flex-start; -ms-flex-pack: flex-start; justify-content: flex-start; text-align: left; text-anchor: end}.ct-grid{stroke: rgba(0, 0, 0, .2); stroke-width: 1px; stroke-dasharray: 2px}.ct-point{stroke-width: 10px; stroke-linecap: round}.ct-line{stroke-width: 4px}.ct-area{stroke: none; fill-opacity: .1}.ct-bar{fill: none; stroke-width: 10px}.ct-slice-donut{fill: none; stroke-width: 60px}.ct-series-a .ct-bar,.ct-series-a .ct-line,.ct-series-a .ct-point,.ct-series-a .ct-slice-donut{stroke: #d70206}.ct-series-a .ct-area,.ct-series-a .ct-slice-pie{fill: #d70206}.ct-series-b .ct-bar,.ct-series-b .ct-line,.ct-series-b .ct-point,.ct-series-b .ct-slice-donut{stroke: #f05b4f}.ct-series-b .ct-area,.ct-series-b .ct-slice-pie{fill: #f05b4f}.ct-series-c .ct-bar,.ct-series-c .ct-line,.ct-series-c .ct-point,.ct-series-c .ct-slice-donut{stroke: #f4c63d}.ct-series-c .ct-area,.ct-series-c .ct-slice-pie{fill: #f4c63d}.ct-series-d .ct-bar,.ct-series-d .ct-line,.ct-series-d .ct-point,.ct-series-d .ct-slice-donut{stroke: #d17905}.ct-series-d .ct-area,.ct-series-d .ct-slice-pie{fill: #d17905}.ct-series-e .ct-bar,.ct-series-e .ct-line,.ct-series-e .ct-point,.ct-series-e .ct-slice-donut{stroke: #453d3f}.ct-series-e .ct-area,.ct-series-e .ct-slice-pie{fill: #453d3f}.ct-series-f .ct-bar,.ct-series-f .ct-line,.ct-series-f .ct-point,.ct-series-f .ct-slice-donut{stroke: #59922b}.ct-series-f .ct-area,.ct-series-f .ct-slice-pie{fill: #59922b}.ct-series-g .ct-bar,.ct-series-g .ct-line,.ct-series-g .ct-point,.ct-series-g .ct-slice-donut{stroke: #0544d3}.ct-series-g .ct-area,.ct-series-g .ct-slice-pie{fill: #0544d3}.ct-series-h .ct-bar,.ct-series-h .ct-line,.ct-series-h .ct-point,.ct-series-h .ct-slice-donut{stroke: #6b0392}.ct-series-h .ct-area,.ct-series-h .ct-slice-pie{fill: #6b0392}.ct-series-i .ct-bar,.ct-series-i .ct-line,.ct-series-i .ct-point,.ct-series-i .ct-slice-donut{stroke: #f05b4f}.ct-series-i .ct-area,.ct-series-i .ct-slice-pie{fill: #f05b4f}.ct-series-j .ct-bar,.ct-series-j .ct-line,.ct-series-j .ct-point,.ct-series-j .ct-slice-donut{stroke: #dda458}.ct-series-j .ct-area,.ct-series-j .ct-slice-pie{fill: #dda458}.ct-series-k .ct-bar,.ct-series-k .ct-line,.ct-series-k .ct-point,.ct-series-k .ct-slice-donut{stroke: #eacf7d}.ct-series-k .ct-area,.ct-series-k .ct-slice-pie{fill: #eacf7d}.ct-series-l .ct-bar,.ct-series-l .ct-line,.ct-series-l .ct-point,.ct-series-l .ct-slice-donut{stroke: #86797d}.ct-series-l .ct-area,.ct-series-l .ct-slice-pie{fill: #86797d}.ct-series-m .ct-bar,.ct-series-m .ct-line,.ct-series-m .ct-point,.ct-series-m .ct-slice-donut{stroke: #b2c326}.ct-series-m .ct-area,.ct-series-m .ct-slice-pie{fill: #b2c326}.ct-series-n .ct-bar,.ct-series-n .ct-line,.ct-series-n .ct-point,.ct-series-n .ct-slice-donut{stroke: #6188e2}.ct-series-n .ct-area,.ct-series-n .ct-slice-pie{fill: #6188e2}.ct-series-o .ct-bar,.ct-series-o .ct-line,.ct-series-o .ct-point,.ct-series-o .ct-slice-donut{stroke: #a748ca}.ct-series-o .ct-area,.ct-series-o .ct-slice-pie{fill: #a748ca}.ct-square{display: block; position: relative; width: 100%}.ct-square:before{display: block; width: 0; padding-bottom: 100%}.ct-square:after{display: table}.ct-square>svg{display: block; position: absolute; top: 0; left: 0}.ct-minor-second{display: block; position: relative; width: 100%}.ct-minor-second:before{display: block; width: 0; padding-bottom: 93.75%}.ct-minor-second:after{display: table}.ct-minor-second>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-second{display: block; position: relative; width: 100%}.ct-major-second:before{display: block; width: 0; padding-bottom: 88.8888888889%}.ct-major-second:after{display: table}.ct-major-second>svg{display: block; position: absolute; top: 0; left: 0}.ct-minor-third{display: block; position: relative; width: 100%}.ct-minor-third:before{display: block; width: 0; padding-bottom: 83.3333333333%}.ct-minor-third:after{display: table}.ct-minor-third>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-third{display: block; position: relative; width: 100%}.ct-major-third:before{display: block; width: 0; padding-bottom: 80%}.ct-major-third:after{display: table}.ct-major-third>svg{display: block; position: absolute; top: 0; left: 0}.ct-perfect-fourth{display: block; position: relative; width: 100%}.ct-perfect-fourth:before{display: block; width: 0; padding-bottom: 75%}.ct-perfect-fourth:after{display: table}.ct-perfect-fourth>svg{display: block; position: absolute; top: 0; left: 0}.ct-perfect-fifth{display: block; position: relative; width: 100%}.ct-perfect-fifth:before{display: block; width: 0; padding-bottom: 66.6666666667%}.ct-perfect-fifth:after{display: table}.ct-perfect-fifth>svg{display: block; position: absolute; top: 0; left: 0}.ct-minor-sixth{display: block; position: relative; width: 100%}.ct-minor-sixth:before{display: block; width: 0; padding-bottom: 62.5%}.ct-minor-sixth:after{display: table}.ct-minor-sixth>svg{display: block; position: absolute; top: 0; left: 0}.ct-golden-section{display: block; position: relative; width: 100%}.ct-golden-section:before{display: block; float: left; content: \"\"; width: 0; height: 0; padding-bottom: 61.804697157%}.ct-golden-section:after{content: \"\"; display: table; clear: both}.ct-golden-section>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-sixth{display: block; position: relative; width: 100%}.ct-major-sixth:before{display: block; width: 0; padding-bottom: 60%}.ct-major-sixth:after{display: table}.ct-major-sixth>svg{display: block; position: absolute; top: 0; left: 0}.ct-minor-seventh{display: block; position: relative; width: 100%}.ct-minor-seventh:before{display: block; width: 0; padding-bottom: 56.25%}.ct-minor-seventh:after{display: table}.ct-minor-seventh>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-seventh{display: block; position: relative; width: 100%}.ct-major-seventh:before{display: block; width: 0; padding-bottom: 53.3333333333%}.ct-major-seventh:after{display: table}.ct-major-seventh>svg{display: block; position: absolute; top: 0; left: 0}.ct-octave{display: block; position: relative; width: 100%}.ct-octave:before{display: block; width: 0; padding-bottom: 50%}.ct-octave:after{display: table}.ct-octave>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-tenth{display: block; position: relative; width: 100%}.ct-major-tenth:before{display: block; width: 0; padding-bottom: 40%}.ct-major-tenth:after{display: table}.ct-major-tenth>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-eleventh{display: block; position: relative; width: 100%}.ct-major-eleventh:before{display: block; width: 0; padding-bottom: 37.5%}.ct-major-eleventh:after{display: table}.ct-major-eleventh>svg{display: block; position: absolute; top: 0; left: 0}.ct-major-twelfth{display: block; position: relative; width: 100%}.ct-major-twelfth:before{display: block; width: 0; padding-bottom: 33.3333333333%}.ct-major-twelfth:after{display: table}.ct-major-twelfth>svg{display: block; position: absolute; top: 0; left: 0}.ct-double-octave{display: block; position: relative; width: 100%}.ct-double-octave:before{display: block; width: 0; padding-bottom: 25%}.ct-double-octave:after{display: table}.ct-double-octave>svg{display: block; position: absolute; top: 0; left: 0}</style><body><div id=\"wrapper\" style=\"width:100%;height:inherit\"> <ul class=\"tab\"> <li><a href=\"javascript:void(0)\" class=\"tablinks\" id=\"default\" onclick=\"changeTab(event, 'Top')\">Top</a></li><li><a href=\"javascript:void(0)\" class=\"tablinks\" onclick=\"changeTab(event, 'Relations')\">Relations</a></li><li><a href=\"javascript:void(0)\" class=\"tablinks\" onclick=\"changeTab(event, 'Rules')\">Rules</a></li><li id=\"chart_tab\" style=\"display:none\"><a href=\"javascript:void(0)\" class=\"tablinks\">Chart</a></li></ul> <div id=\"Top\" class=\"tabcontent\"> <h3>Top</h3> </div><div id=\"Relations\" class=\"tabcontent\"> <h3>Relations table</h3> <button onclick=\"toggle_precision()\">Toggle number precision</button> <table id='Rel_table'> <thead> <tr> <th data-sort-method=\"text\"><span class=\"text\">Name</span></th> <th data-sort-method=\"text\"><span class=\"text\">ID</span></th> <th data-sort-method=\"time\"><span class=\"text\">Total Time</span></th> <th data-sort-method=\"time\"><span class=\"text\">Non Rec Time</span></th> <th data-sort-method=\"time\"><span class=\"text\">Rec Time</span></th> <th data-sort-method=\"time\"><span class=\"text\">Copy Time</span></th> <th data-sort-method=\"number\"><span class=\"text\">Tuples</span></th> <th data-sort-method=\"number\"><span class=\"text\">% of Time</span></th> <th data-sort-method=\"number\"><span class=\"text\">% of Tuples</span></th> <th data-sort-method=\"text\"><span class=\"text\">Source</span></th> </tr></thead> <tbody id=\"Rel_table_body\"> </tbody> </table> <hr/> <div id=\"rulesofrel\" style=\"display:none\"> <h3>Rules of Relation</h3> <button>Graph selected (not implemented: seems useless)</button> <p>Graph relation selected below (ID begins with R)</p><table id=\"rulesofrel_table\"> <thead> <tr> <th data-sort-method=\"text\">Name</th> <th data-sort-method=\"text\">ID</th> <th data-sort-method=\"time\">Total Time</th> <th data-sort-method=\"time\">Non Rec Time</th> <th data-sort-method=\"time\">Rec Time</th> <th data-sort-method=\"time\">Copy Time</th> <th data-sort-method=\"number\">Tuples</th> <th data-sort-method=\"number\">% of Time</th> <th data-sort-method=\"number\">% of Tuples</th> <th data-sort-method=\"text\">Source</th> </tr></thead> <tbody id=\"rulesofrel_body\"> </tbody> </table> </div></div><div id=\"Rules\" class=\"tabcontent\"> <h3>Rules table</h3> <button onclick=\"toggle_precision()\">Toggle number precision</button> <table id='Rul_table'> <thead> <tr> <th data-sort-method=\"text\">Name</th> <th data-sort-method=\"text\">ID</th> <th data-sort-method=\"time\">Total Time</th> <th data-sort-method=\"time\">Non Rec Time</th> <th data-sort-method=\"time\">Rec Time</th> <th data-sort-method=\"time\">Copy Time</th> <th data-sort-method=\"number\">Tuples</th> <th data-sort-method=\"number\">% of Time</th> <th data-sort-method=\"number\">% of Tuples</th> <th data-sort-method=\"text\">Source</th> </tr></thead> <tbody id=\"Rul_table_body\"> </tbody> </table> <hr/> <div id=\"rulver\" style=\"display:none\"> <h3>Rule Versions Table</h3> <p>Graph recursive rule selected below (ID begins with C)</p><button>Graph selected (not implemented: seems useless)</button><br/> <button onclick=\"showChart()\">Graph versions of selected</button> <table id='rulvertable'> <thead> <tr> <th data-sort-method=\"text\">Name</th> <th data-sort-method=\"text\">ID</th> <th data-sort-method=\"time\">Total Time</th> <th data-sort-method=\"time\">Non Rec Time</th> <th data-sort-method=\"time\">Rec Time</th> <th data-sort-method=\"time\">Copy Time</th> <th data-sort-method=\"number\">Tuples</th> <th data-sort-method=\"number\">Ver</th> <th data-sort-method=\"number\">% of Time</th> <th data-sort-method=\"number\">% of Tuples</th> <th data-sort-method=\"text\">Source</th> </tr></thead> <tbody id=\"rulver_body\"> </tbody> </table> </div></div><div id=\"chart\" class=\"tabcontent\"> <h1>Total run time</h1> <div class=\"ct-chart1\"></div><h1>Total number of tuples</h1> <div class=\"ct-chart2\"></div><button onclick=\"show_graph_vals=!show_graph_vals;showChart();\">Toggle values</button> </div></div></body><script>/*! * tablesort v4.1.0 (2016-12-29) * http://tristen.ca/tablesort/demo/ * Copyright (c) 2016 ; Licensed MIT */!function(){function a(b,c){if(!(this instanceof a))return new a(b,c);if(!b||\"TABLE\"!==b.tagName)throw new Error(\"Element must be a table\");this.init(b,c||{})}var b=[],c=function(a){var b;return window.CustomEvent&&\"function\"==typeof window.CustomEvent?b=new CustomEvent(a):(b=document.createEvent(\"CustomEvent\"),b.initCustomEvent(a,!1,!1,void 0)),b},d=function(a){return a.getAttribute(\"data-sort\")||a.textContent||a.innerText||\"\"},e=function(a,b){return a=a.toLowerCase(),b=b.toLowerCase(),a===b?0:a<b?1:-1},f=function(a,b){return function(c,d){var e=a(c.td,d.td);return 0===e?b?d.index-c.index:c.index-d.index:e}};a.extend=function(a,c,d){if(\"function\"!=typeof c||\"function\"!=typeof d)throw new Error(\"Pattern and sort must be a function\");b.push({name:a,pattern:c,sort:d})},a.prototype={init:function(a,b){var c,d,e,f,g=this;if(g.table=a,g.thead=!1,g.options=b,a.rows&&a.rows.length>0)if(a.tHead&&a.tHead.rows.length>0){for(e=0;e<a.tHead.rows.length;e++)if(\"thead\"===a.tHead.rows[e].getAttribute(\"data-sort-method\")){c=a.tHead.rows[e];break}c||(c=a.tHead.rows[a.tHead.rows.length-1]),g.thead=!0}else c=a.rows[0];if(c){var h=function(){g.current&&g.current!==this&&g.current.removeAttribute(\"aria-sort\"),g.current=this,g.sortTable(this)};for(e=0;e<c.cells.length;e++)f=c.cells[e],f.setAttribute(\"role\",\"columnheader\"),\"none\"!==f.getAttribute(\"data-sort-method\")&&(f.tabindex=0,f.addEventListener(\"click\",h,!1),null!==f.getAttribute(\"data-sort-default\")&&(d=f));d&&(g.current=d,g.sortTable(d))}},sortTable:function(a,g){var h=this,i=a.cellIndex,j=e,k=\"\",l=[],m=h.thead?0:1,n=a.getAttribute(\"data-sort-method\"),o=a.getAttribute(\"aria-sort\");if(h.table.dispatchEvent(c(\"beforeSort\")),g||(o=\"ascending\"===o?\"descending\":\"descending\"===o?\"ascending\":h.options.descending?\"ascending\":\"descending\",a.setAttribute(\"aria-sort\",o)),!(h.table.rows.length<2)){if(!n){for(;l.length<3&&m<h.table.tBodies[0].rows.length;)k=d(h.table.tBodies[0].rows[m].cells[i]),k=k.trim(),k.length>0&&l.push(k),m++;if(!l)return}for(m=0;m<b.length;m++)if(k=b[m],n){if(k.name===n){j=k.sort;break}}else if(l.every(k.pattern)){j=k.sort;break}for(h.col=i,m=0;m<h.table.tBodies.length;m++){var p,q=[],r={},s=0,t=0;if(!(h.table.tBodies[m].rows.length<2)){for(p=0;p<h.table.tBodies[m].rows.length;p++)k=h.table.tBodies[m].rows[p],\"none\"===k.getAttribute(\"data-sort-method\")?r[s]=k:q.push({tr:k,td:d(k.cells[h.col]),index:s}),s++;for(\"descending\"===o?(q.sort(f(j,!0)),q.reverse()):q.sort(f(j,!1)),p=0;p<s;p++)r[p]?(k=r[p],t++):k=q[p-t].tr,h.table.tBodies[m].appendChild(k)}}h.table.dispatchEvent(c(\"afterSort\"))}},refresh:function(){void 0!==this.current&&this.sortTable(this.current,!0)}},\"undefined\"!=typeof module&&module.exports?module.exports=a:window.Tablesort=a}(); /*Chartist.js 0.10.0 * Copyright © 2016 Gion Kunz * Free to use under either the WTFPL license or the MIT license. * https://raw.githubusercontent.com/gionkunz/chartist-js/master/LICENSE-WTFPL * https://raw.githubusercontent.com/gionkunz/chartist-js/master/LICENSE-MIT */!function(a,b){\"function\"==typeof define&&define.amd?define(\"Chartist\",[],function(){return a.Chartist=b()}):\"object\"==typeof exports?module.exports=b():a.Chartist=b()}(this,function(){var a={version:\"0.10.0\"};return function(a,b,c){\"use strict\";c.namespaces={svg:\"http://www.w3.org/2000/svg\",xmlns:\"http://www.w3.org/2000/xmlns/\",xhtml:\"http://www.w3.org/1999/xhtml\",xlink:\"http://www.w3.org/1999/xlink\",ct:\"http://gionkunz.github.com/chartist-js/ct\"},c.noop=function(a){return a},c.alphaNumerate=function(a){return String.fromCharCode(97+a%26)},c.extend=function(a){var b,d,e;for(a=a||{},b=1;b<arguments.length;b++){d=arguments[b];for(var f in d)e=d[f],\"object\"!=typeof e||null===e||e instanceof Array?a[f]=e:a[f]=c.extend(a[f],e)}return a},c.replaceAll=function(a,b,c){return a.replace(new RegExp(b,\"g\"),c)},c.ensureUnit=function(a,b){return\"number\"==typeof a&&(a+=b),a},c.quantity=function(a){if(\"string\"==typeof a){var b=/^(\\d+)\\s*(.*)$/g.exec(a);return{value:+b[1],unit:b[2]||void 0}}return{value:a}},c.querySelector=function(a){return a instanceof Node?a:b.querySelector(a)},c.times=function(a){return Array.apply(null,new Array(a))},c.sum=function(a,b){return a+(b?b:0)},c.mapMultiply=function(a){return function(b){return b*a}},c.mapAdd=function(a){return function(b){return b+a}},c.serialMap=function(a,b){var d=[],e=Math.max.apply(null,a.map(function(a){return a.length}));return c.times(e).forEach(function(c,e){var f=a.map(function(a){return a[e]});d[e]=b.apply(null,f)}),d},c.roundWithPrecision=function(a,b){var d=Math.pow(10,b||c.precision);return Math.round(a*d)/d},c.precision=8,c.escapingMap={\"&\":\"&amp;\",\"<\":\"&lt;\",\">\":\"&gt;\",'\"':\"&quot;\",\"'\":\"&#039;\"},c.serialize=function(a){return null===a||void 0===a?a:(\"number\"==typeof a?a=\"\"+a:\"object\"==typeof a&&(a=JSON.stringify({data:a})),Object.keys(c.escapingMap).reduce(function(a,b){return c.replaceAll(a,b,c.escapingMap[b])},a))},c.deserialize=function(a){if(\"string\"!=typeof a)return a;a=Object.keys(c.escapingMap).reduce(function(a,b){return c.replaceAll(a,c.escapingMap[b],b)},a);try{a=JSON.parse(a),a=void 0!==a.data?a.data:a}catch(b){}return a},c.createSvg=function(a,b,d,e){var f;return b=b||\"100%\",d=d||\"100%\",Array.prototype.slice.call(a.querySelectorAll(\"svg\")).filter(function(a){return a.getAttributeNS(c.namespaces.xmlns,\"ct\")}).forEach(function(b){a.removeChild(b)}),f=new c.Svg(\"svg\").attr({width:b,height:d}).addClass(e).attr({style:\"width: \"+b+\"; height: \"+d+\";\"}),a.appendChild(f._node),f},c.normalizeData=function(a,b,d){var e,f={raw:a,normalized:{}};return f.normalized.series=c.getDataArray({series:a.series||[]},b,d),e=f.normalized.series.every(function(a){return a instanceof Array})?Math.max.apply(null,f.normalized.series.map(function(a){return a.length})):f.normalized.series.length,f.normalized.labels=(a.labels||[]).slice(),Array.prototype.push.apply(f.normalized.labels,c.times(Math.max(0,e-f.normalized.labels.length)).map(function(){return\"\"})),b&&c.reverseData(f.normalized),f},c.safeHasProperty=function(a,b){return null!==a&&\"object\"==typeof a&&a.hasOwnProperty(b)},c.isDataHoleValue=function(a){return null===a||void 0===a||\"number\"==typeof a&&isNaN(a)},c.reverseData=function(a){a.labels.reverse(),a.series.reverse();for(var b=0;b<a.series.length;b++)\"object\"==typeof a.series[b]&&void 0!==a.series[b].data?a.series[b].data.reverse():a.series[b]instanceof Array&&a.series[b].reverse()},c.getDataArray=function(a,b,d){function e(a){if(c.safeHasProperty(a,\"value\"))return e(a.value);if(c.safeHasProperty(a,\"data\"))return e(a.data);if(a instanceof Array)return a.map(e);if(!c.isDataHoleValue(a)){if(d){var b={};return\"string\"==typeof d?b[d]=c.getNumberOrUndefined(a):b.y=c.getNumberOrUndefined(a),b.x=a.hasOwnProperty(\"x\")?c.getNumberOrUndefined(a.x):b.x,b.y=a.hasOwnProperty(\"y\")?c.getNumberOrUndefined(a.y):b.y,b}return c.getNumberOrUndefined(a)}}return a.series.map(e)},c.normalizePadding=function(a,b){return b=b||0,\"number\"==typeof a?{top:a,right:a,bottom:a,left:a}:{top:\"number\"==typeof a.top?a.top:b,right:\"number\"==typeof a.right?a.right:b,bottom:\"number\"==typeof a.bottom?a.bottom:b,left:\"number\"==typeof a.left?a.left:b}},c.getMetaData=function(a,b){var c=a.data?a.data[b]:a[b];return c?c.meta:void 0},c.orderOfMagnitude=function(a){return Math.floor(Math.log(Math.abs(a))/Math.LN10)},c.projectLength=function(a,b,c){return b/c.range*a},c.getAvailableHeight=function(a,b){return Math.max((c.quantity(b.height).value||a.height())-(b.chartPadding.top+b.chartPadding.bottom)-b.axisX.offset,0)},c.getHighLow=function(a,b,d){function e(a){if(void 0!==a)if(a instanceof Array)for(var b=0;b<a.length;b++)e(a[b]);else{var c=d?+a[d]:+a;g&&c>f.high&&(f.high=c),h&&c<f.low&&(f.low=c)}}b=c.extend({},b,d?b[\"axis\"+d.toUpperCase()]:{});var f={high:void 0===b.high?-Number.MAX_VALUE:+b.high,low:void 0===b.low?Number.MAX_VALUE:+b.low},g=void 0===b.high,h=void 0===b.low;return(g||h)&&e(a),(b.referenceValue||0===b.referenceValue)&&(f.high=Math.max(b.referenceValue,f.high),f.low=Math.min(b.referenceValue,f.low)),f.high<=f.low&&(0===f.low?f.high=1:f.low<0?f.high=0:f.high>0?f.low=0:(f.high=1,f.low=0)),f},c.isNumeric=function(a){return null!==a&&isFinite(a)},c.isFalseyButZero=function(a){return!a&&0!==a},c.getNumberOrUndefined=function(a){return c.isNumeric(a)?+a:void 0},c.isMultiValue=function(a){return\"object\"==typeof a&&(\"x\"in a||\"y\"in a)},c.getMultiValue=function(a,b){return c.isMultiValue(a)?c.getNumberOrUndefined(a[b||\"y\"]):c.getNumberOrUndefined(a)},c.rho=function(a){function b(a,c){return a%c===0?c:b(c,a%c)}function c(a){return a*a+1}if(1===a)return a;var d,e=2,f=2;if(a%2===0)return 2;do e=c(e)%a,f=c(c(f))%a,d=b(Math.abs(e-f),a);while(1===d);return d},c.getBounds=function(a,b,d,e){function f(a,b){return a===(a+=b)&&(a*=1+(b>0?o:-o)),a}var g,h,i,j=0,k={high:b.high,low:b.low};k.valueRange=k.high-k.low,k.oom=c.orderOfMagnitude(k.valueRange),k.step=Math.pow(10,k.oom),k.min=Math.floor(k.low/k.step)*k.step,k.max=Math.ceil(k.high/k.step)*k.step,k.range=k.max-k.min,k.numberOfSteps=Math.round(k.range/k.step);var l=c.projectLength(a,k.step,k),m=l<d,n=e?c.rho(k.range):0;if(e&&c.projectLength(a,1,k)>=d)k.step=1;else if(e&&n<k.step&&c.projectLength(a,n,k)>=d)k.step=n;else for(;;){if(m&&c.projectLength(a,k.step,k)<=d)k.step*=2;else{if(m||!(c.projectLength(a,k.step/2,k)>=d))break;if(k.step/=2,e&&k.step%1!==0){k.step*=2;break}}if(j++>1e3)throw new Error(\"Exceeded maximum number of iterations while optimizing scale step!\")}var o=2.221e-16;for(k.step=Math.max(k.step,o),h=k.min,i=k.max;h+k.step<=k.low;)h=f(h,k.step);for(;i-k.step>=k.high;)i=f(i,-k.step);k.min=h,k.max=i,k.range=k.max-k.min;var p=[];for(g=k.min;g<=k.max;g=f(g,k.step)){var q=c.roundWithPrecision(g);q!==p[p.length-1]&&p.push(q)}return k.values=p,k},c.polarToCartesian=function(a,b,c,d){var e=(d-90)*Math.PI/180;return{x:a+c*Math.cos(e),y:b+c*Math.sin(e)}},c.createChartRect=function(a,b,d){var e=!(!b.axisX&&!b.axisY),f=e?b.axisY.offset:0,g=e?b.axisX.offset:0,h=a.width()||c.quantity(b.width).value||0,i=a.height()||c.quantity(b.height).value||0,j=c.normalizePadding(b.chartPadding,d);h=Math.max(h,f+j.left+j.right),i=Math.max(i,g+j.top+j.bottom);var k={padding:j,width:function(){return this.x2-this.x1},height:function(){return this.y1-this.y2}};return e?(\"start\"===b.axisX.position?(k.y2=j.top+g,k.y1=Math.max(i-j.bottom,k.y2+1)):(k.y2=j.top,k.y1=Math.max(i-j.bottom-g,k.y2+1)),\"start\"===b.axisY.position?(k.x1=j.left+f,k.x2=Math.max(h-j.right,k.x1+1)):(k.x1=j.left,k.x2=Math.max(h-j.right-f,k.x1+1))):(k.x1=j.left,k.x2=Math.max(h-j.right,k.x1+1),k.y2=j.top,k.y1=Math.max(i-j.bottom,k.y2+1)),k},c.createGrid=function(a,b,d,e,f,g,h,i){var j={};j[d.units.pos+\"1\"]=a,j[d.units.pos+\"2\"]=a,j[d.counterUnits.pos+\"1\"]=e,j[d.counterUnits.pos+\"2\"]=e+f;var k=g.elem(\"line\",j,h.join(\" \"));i.emit(\"draw\",c.extend({type:\"grid\",axis:d,index:b,group:g,element:k},j))},c.createGridBackground=function(a,b,c,d){var e=a.elem(\"rect\",{x:b.x1,y:b.y2,width:b.width(),height:b.height()},c,!0);d.emit(\"draw\",{type:\"gridBackground\",group:a,element:e})},c.createLabel=function(a,b,d,e,f,g,h,i,j,k,l){var m,n={};if(n[f.units.pos]=a+h[f.units.pos],n[f.counterUnits.pos]=h[f.counterUnits.pos],n[f.units.len]=b,n[f.counterUnits.len]=Math.max(0,g-10),k){var o='<span class=\"'+j.join(\" \")+'\" style=\"'+f.units.len+\": \"+Math.round(n[f.units.len])+\"px; \"+f.counterUnits.len+\": \"+Math.round(n[f.counterUnits.len])+'px\">'+e[d]+\"</span>\";m=i.foreignObject(o,c.extend({style:\"overflow: visible;\"},n))}else m=i.elem(\"text\",n,j.join(\" \")).text(e[d]);l.emit(\"draw\",c.extend({type:\"label\",axis:f,index:d,group:i,element:m,text:e[d]},n))},c.getSeriesOption=function(a,b,c){if(a.name&&b.series&&b.series[a.name]){var d=b.series[a.name];return d.hasOwnProperty(c)?d[c]:b[c]}return b[c]},c.optionsProvider=function(b,d,e){function f(b){var f=h;if(h=c.extend({},j),d)for(i=0;i<d.length;i++){var g=a.matchMedia(d[i][0]);g.matches&&(h=c.extend(h,d[i][1]))}e&&b&&e.emit(\"optionsChanged\",{previousOptions:f,currentOptions:h})}function g(){k.forEach(function(a){a.removeListener(f)})}var h,i,j=c.extend({},b),k=[];if(!a.matchMedia)throw\"window.matchMedia not found! Make sure you're using a polyfill.\";if(d)for(i=0;i<d.length;i++){var l=a.matchMedia(d[i][0]);l.addListener(f),k.push(l)}return f(),{removeMediaQueryListeners:g,getCurrentOptions:function(){return c.extend({},h)}}},c.splitIntoSegments=function(a,b,d){var e={increasingX:!1,fillHoles:!1};d=c.extend({},e,d);for(var f=[],g=!0,h=0;h<a.length;h+=2)void 0===c.getMultiValue(b[h/2].value)?d.fillHoles||(g=!0):(d.increasingX&&h>=2&&a[h]<=a[h-2]&&(g=!0),g&&(f.push({pathCoordinates:[],valueData:[]}),g=!1),f[f.length-1].pathCoordinates.push(a[h],a[h+1]),f[f.length-1].valueData.push(b[h/2]));return f}}(window,document,a),function(a,b,c){\"use strict\";c.Interpolation={},c.Interpolation.none=function(a){var b={fillHoles:!1};return a=c.extend({},b,a),function(b,d){for(var e=new c.Svg.Path,f=!0,g=0;g<b.length;g+=2){var h=b[g],i=b[g+1],j=d[g/2];void 0!==c.getMultiValue(j.value)?(f?e.move(h,i,!1,j):e.line(h,i,!1,j),f=!1):a.fillHoles||(f=!0)}return e}},c.Interpolation.simple=function(a){var b={divisor:2,fillHoles:!1};a=c.extend({},b,a);var d=1/Math.max(1,a.divisor);return function(b,e){for(var f,g,h,i=new c.Svg.Path,j=0;j<b.length;j+=2){var k=b[j],l=b[j+1],m=(k-f)*d,n=e[j/2];void 0!==n.value?(void 0===h?i.move(k,l,!1,n):i.curve(f+m,g,k-m,l,k,l,!1,n),f=k,g=l,h=n):a.fillHoles||(f=k=h=void 0)}return i}},c.Interpolation.cardinal=function(a){var b={tension:1,fillHoles:!1};a=c.extend({},b,a);var d=Math.min(1,Math.max(0,a.tension)),e=1-d;return function f(b,g){var h=c.splitIntoSegments(b,g,{fillHoles:a.fillHoles});if(h.length){if(h.length>1){var i=[];return h.forEach(function(a){i.push(f(a.pathCoordinates,a.valueData))}),c.Svg.Path.join(i)}if(b=h[0].pathCoordinates,g=h[0].valueData,b.length<=4)return c.Interpolation.none()(b,g);for(var j,k=(new c.Svg.Path).move(b[0],b[1],!1,g[0]),l=0,m=b.length;m-2*!j>l;l+=2){var n=[{x:+b[l-2],y:+b[l-1]},{x:+b[l],y:+b[l+1]},{x:+b[l+2],y:+b[l+3]},{x:+b[l+4],y:+b[l+5]}];j?l?m-4===l?n[3]={x:+b[0],y:+b[1]}:m-2===l&&(n[2]={x:+b[0],y:+b[1]},n[3]={x:+b[2],y:+b[3]}):n[0]={x:+b[m-2],y:+b[m-1]}:m-4===l?n[3]=n[2]:l||(n[0]={x:+b[l],y:+b[l+1]}),k.curve(d*(-n[0].x+6*n[1].x+n[2].x)/6+e*n[2].x,d*(-n[0].y+6*n[1].y+n[2].y)/6+e*n[2].y,d*(n[1].x+6*n[2].x-n[3].x)/6+e*n[2].x,d*(n[1].y+6*n[2].y-n[3].y)/6+e*n[2].y,n[2].x,n[2].y,!1,g[(l+2)/2])}return k}return c.Interpolation.none()([])}},c.Interpolation.monotoneCubic=function(a){var b={fillHoles:!1};return a=c.extend({},b,a),function d(b,e){var f=c.splitIntoSegments(b,e,{fillHoles:a.fillHoles,increasingX:!0});if(f.length){if(f.length>1){var g=[];return f.forEach(function(a){g.push(d(a.pathCoordinates,a.valueData))}),c.Svg.Path.join(g)}if(b=f[0].pathCoordinates,e=f[0].valueData,b.length<=4)return c.Interpolation.none()(b,e);var h,i,j=[],k=[],l=b.length/2,m=[],n=[],o=[],p=[];for(h=0;h<l;h++)j[h]=b[2*h],k[h]=b[2*h+1];for(h=0;h<l-1;h++)o[h]=k[h+1]-k[h],p[h]=j[h+1]-j[h],n[h]=o[h]/p[h];for(m[0]=n[0],m[l-1]=n[l-2],h=1;h<l-1;h++)0===n[h]||0===n[h-1]||n[h-1]>0!=n[h]>0?m[h]=0:(m[h]=3*(p[h-1]+p[h])/((2*p[h]+p[h-1])/n[h-1]+(p[h]+2*p[h-1])/n[h]),isFinite(m[h])||(m[h]=0));for(i=(new c.Svg.Path).move(j[0],k[0],!1,e[0]),h=0;h<l-1;h++)i.curve(j[h]+p[h]/3,k[h]+m[h]*p[h]/3,j[h+1]-p[h]/3,k[h+1]-m[h+1]*p[h]/3,j[h+1],k[h+1],!1,e[h+1]);return i}return c.Interpolation.none()([])}},c.Interpolation.step=function(a){var b={postpone:!0,fillHoles:!1};return a=c.extend({},b,a),function(b,d){for(var e,f,g,h=new c.Svg.Path,i=0;i<b.length;i+=2){var j=b[i],k=b[i+1],l=d[i/2];void 0!==l.value?(void 0===g?h.move(j,k,!1,l):(a.postpone?h.line(j,f,!1,g):h.line(e,k,!1,l),h.line(j,k,!1,l)),e=j,f=k,g=l):a.fillHoles||(e=f=g=void 0)}return h}}}(window,document,a),function(a,b,c){\"use strict\";c.EventEmitter=function(){function a(a,b){d[a]=d[a]||[],d[a].push(b)}function b(a,b){d[a]&&(b?(d[a].splice(d[a].indexOf(b),1),0===d[a].length&&delete d[a]):delete d[a])}function c(a,b){d[a]&&d[a].forEach(function(a){a(b)}),d[\"*\"]&&d[\"*\"].forEach(function(c){c(a,b)})}var d=[];return{addEventHandler:a,removeEventHandler:b,emit:c}}}(window,document,a),function(a,b,c){\"use strict\";function d(a){var b=[];if(a.length)for(var c=0;c<a.length;c++)b.push(a[c]);return b}function e(a,b){var d=b||this.prototype||c.Class,e=Object.create(d);c.Class.cloneDefinitions(e,a);var f=function(){var a,b=e.constructor||function(){};return a=this===c?Object.create(e):this,b.apply(a,Array.prototype.slice.call(arguments,0)),a};return f.prototype=e,f[\"super\"]=d,f.extend=this.extend,f}function f(){var a=d(arguments),b=a[0];return a.splice(1,a.length-1).forEach(function(a){Object.getOwnPropertyNames(a).forEach(function(c){delete b[c],Object.defineProperty(b,c,Object.getOwnPropertyDescriptor(a,c))})}),b}c.Class={extend:e,cloneDefinitions:f}}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,d){return a&&(this.data=a||{},this.data.labels=this.data.labels||[],this.data.series=this.data.series||[],this.eventEmitter.emit(\"data\",{type:\"update\",data:this.data})),b&&(this.options=c.extend({},d?this.options:this.defaultOptions,b),this.initializeTimeoutId||(this.optionsProvider.removeMediaQueryListeners(),this.optionsProvider=c.optionsProvider(this.options,this.responsiveOptions,this.eventEmitter))),this.initializeTimeoutId||this.createChart(this.optionsProvider.getCurrentOptions()),this}function e(){return this.initializeTimeoutId?a.clearTimeout(this.initializeTimeoutId):(a.removeEventListener(\"resize\",this.resizeListener),this.optionsProvider.removeMediaQueryListeners()),this}function f(a,b){return this.eventEmitter.addEventHandler(a,b),this}function g(a,b){return this.eventEmitter.removeEventHandler(a,b),this}function h(){a.addEventListener(\"resize\",this.resizeListener),this.optionsProvider=c.optionsProvider(this.options,this.responsiveOptions,this.eventEmitter),this.eventEmitter.addEventHandler(\"optionsChanged\",function(){this.update()}.bind(this)),this.options.plugins&&this.options.plugins.forEach(function(a){a instanceof Array?a[0](this,a[1]):a(this)}.bind(this)),this.eventEmitter.emit(\"data\",{type:\"initial\",data:this.data}),this.createChart(this.optionsProvider.getCurrentOptions()),this.initializeTimeoutId=void 0}function i(a,b,d,e,f){this.container=c.querySelector(a),this.data=b||{},this.data.labels=this.data.labels||[],this.data.series=this.data.series||[],this.defaultOptions=d,this.options=e,this.responsiveOptions=f,this.eventEmitter=c.EventEmitter(),this.supportsForeignObject=c.Svg.isSupported(\"Extensibility\"),this.supportsAnimations=c.Svg.isSupported(\"AnimationEventsAttribute\"),this.resizeListener=function(){this.update()}.bind(this),this.container&&(this.container.__chartist__&&this.container.__chartist__.detach(),this.container.__chartist__=this),this.initializeTimeoutId=setTimeout(h.bind(this),0)}c.Base=c.Class.extend({constructor:i,optionsProvider:void 0,container:void 0,svg:void 0,eventEmitter:void 0,createChart:function(){throw new Error(\"Base chart type can't be instantiated!\")},update:d,detach:e,on:f,off:g,version:c.version,supportsForeignObject:!1})}(window,document,a),function(a,b,c){\"use strict\";function d(a,d,e,f,g){a instanceof Element?this._node=a:(this._node=b.createElementNS(c.namespaces.svg,a),\"svg\"===a&&this.attr({\"xmlns:ct\":c.namespaces.ct})),d&&this.attr(d),e&&this.addClass(e),f&&(g&&f._node.firstChild?f._node.insertBefore(this._node,f._node.firstChild):f._node.appendChild(this._node))}function e(a,b){return\"string\"==typeof a?b?this._node.getAttributeNS(b,a):this._node.getAttribute(a):(Object.keys(a).forEach(function(b){if(void 0!==a[b])if(b.indexOf(\":\")!==-1){var d=b.split(\":\");this._node.setAttributeNS(c.namespaces[d[0]],b,a[b])}else this._node.setAttribute(b,a[b])}.bind(this)),this)}function f(a,b,d,e){return new c.Svg(a,b,d,this,e)}function g(){return this._node.parentNode instanceof SVGElement?new c.Svg(this._node.parentNode):null}function h(){for(var a=this._node;\"svg\"!==a.nodeName;)a=a.parentNode;return new c.Svg(a)}function i(a){var b=this._node.querySelector(a);return b?new c.Svg(b):null}function j(a){var b=this._node.querySelectorAll(a);return b.length?new c.Svg.List(b):null}function k(){return this._node}function l(a,d,e,f){if(\"string\"==typeof a){var g=b.createElement(\"div\");g.innerHTML=a,a=g.firstChild}a.setAttribute(\"xmlns\",c.namespaces.xmlns);var h=this.elem(\"foreignObject\",d,e,f);return h._node.appendChild(a),h}function m(a){return this._node.appendChild(b.createTextNode(a)),this}function n(){for(;this._node.firstChild;)this._node.removeChild(this._node.firstChild);return this}function o(){return this._node.parentNode.removeChild(this._node),this.parent()}function p(a){return this._node.parentNode.replaceChild(a._node,this._node),a}function q(a,b){return b&&this._node.firstChild?this._node.insertBefore(a._node,this._node.firstChild):this._node.appendChild(a._node),this}function r(){return this._node.getAttribute(\"class\")?this._node.getAttribute(\"class\").trim().split(/\\s+/):[]}function s(a){return this._node.setAttribute(\"class\",this.classes(this._node).concat(a.trim().split(/\\s+/)).filter(function(a,b,c){return c.indexOf(a)===b}).join(\" \")),this}function t(a){var b=a.trim().split(/\\s+/);return this._node.setAttribute(\"class\",this.classes(this._node).filter(function(a){return b.indexOf(a)===-1}).join(\" \")),this}function u(){return this._node.setAttribute(\"class\",\"\"),this}function v(){return this._node.getBoundingClientRect().height}function w(){return this._node.getBoundingClientRect().width}function x(a,b,d){return void 0===b&&(b=!0),Object.keys(a).forEach(function(e){function f(a,b){var f,g,h,i={};a.easing&&(h=a.easing instanceof Array?a.easing:c.Svg.Easing[a.easing],delete a.easing),a.begin=c.ensureUnit(a.begin,\"ms\"),a.dur=c.ensureUnit(a.dur,\"ms\"),h&&(a.calcMode=\"spline\",a.keySplines=h.join(\" \"),a.keyTimes=\"0;1\"),b&&(a.fill=\"freeze\",i[e]=a.from,this.attr(i),g=c.quantity(a.begin||0).value,a.begin=\"indefinite\"),f=this.elem(\"animate\",c.extend({attributeName:e},a)),b&&setTimeout(function(){try{f._node.beginElement()}catch(b){i[e]=a.to,this.attr(i),f.remove()}}.bind(this),g),d&&f._node.addEventListener(\"beginEvent\",function(){d.emit(\"animationBegin\",{element:this,animate:f._node,params:a})}.bind(this)),f._node.addEventListener(\"endEvent\",function(){d&&d.emit(\"animationEnd\",{element:this,animate:f._node,params:a}),b&&(i[e]=a.to,this.attr(i),f.remove())}.bind(this))}a[e]instanceof Array?a[e].forEach(function(a){f.bind(this)(a,!1)}.bind(this)):f.bind(this)(a[e],b)}.bind(this)),this}function y(a){var b=this;this.svgElements=[];for(var d=0;d<a.length;d++)this.svgElements.push(new c.Svg(a[d]));Object.keys(c.Svg.prototype).filter(function(a){return[\"constructor\",\"parent\",\"querySelector\",\"querySelectorAll\",\"replace\",\"append\",\"classes\",\"height\",\"width\"].indexOf(a)===-1}).forEach(function(a){b[a]=function(){var d=Array.prototype.slice.call(arguments,0);return b.svgElements.forEach(function(b){c.Svg.prototype[a].apply(b,d)}),b}})}c.Svg=c.Class.extend({constructor:d,attr:e,elem:f,parent:g,root:h,querySelector:i,querySelectorAll:j,getNode:k,foreignObject:l,text:m,empty:n,remove:o,replace:p,append:q,classes:r,addClass:s,removeClass:t,removeAllClasses:u,height:v,width:w,animate:x}),c.Svg.isSupported=function(a){return b.implementation.hasFeature(\"http://www.w3.org/TR/SVG11/feature#\"+a,\"1.1\")};var z={easeInSine:[.47,0,.745,.715],easeOutSine:[.39,.575,.565,1],easeInOutSine:[.445,.05,.55,.95],easeInQuad:[.55,.085,.68,.53],easeOutQuad:[.25,.46,.45,.94],easeInOutQuad:[.455,.03,.515,.955],easeInCubic:[.55,.055,.675,.19],easeOutCubic:[.215,.61,.355,1],easeInOutCubic:[.645,.045,.355,1],easeInQuart:[.895,.03,.685,.22],easeOutQuart:[.165,.84,.44,1],easeInOutQuart:[.77,0,.175,1],easeInQuint:[.755,.05,.855,.06],easeOutQuint:[.23,1,.32,1],easeInOutQuint:[.86,0,.07,1],easeInExpo:[.95,.05,.795,.035],easeOutExpo:[.19,1,.22,1],easeInOutExpo:[1,0,0,1],easeInCirc:[.6,.04,.98,.335],easeOutCirc:[.075,.82,.165,1],easeInOutCirc:[.785,.135,.15,.86],easeInBack:[.6,-.28,.735,.045],easeOutBack:[.175,.885,.32,1.275],easeInOutBack:[.68,-.55,.265,1.55]};c.Svg.Easing=z,c.Svg.List=c.Class.extend({constructor:y})}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,d,e,f,g){var h=c.extend({command:f?a.toLowerCase():a.toUpperCase()},b,g?{data:g}:{});d.splice(e,0,h)}function e(a,b){a.forEach(function(c,d){u[c.command.toLowerCase()].forEach(function(e,f){b(c,e,d,f,a)})})}function f(a,b){this.pathElements=[],this.pos=0,this.close=a,this.options=c.extend({},v,b)}function g(a){return void 0!==a?(this.pos=Math.max(0,Math.min(this.pathElements.length,a)),this):this.pos}function h(a){return this.pathElements.splice(this.pos,a),this}function i(a,b,c,e){return d(\"M\",{x:+a,y:+b},this.pathElements,this.pos++,c,e),this}function j(a,b,c,e){return d(\"L\",{x:+a,y:+b},this.pathElements,this.pos++,c,e),this}function k(a,b,c,e,f,g,h,i){return d(\"C\",{x1:+a,y1:+b,x2:+c,y2:+e,x:+f,y:+g},this.pathElements,this.pos++,h,i),this}function l(a,b,c,e,f,g,h,i,j){return d(\"A\",{rx:+a,ry:+b,xAr:+c,lAf:+e,sf:+f,x:+g,y:+h},this.pathElements,this.pos++,i,j),this}function m(a){var b=a.replace(/([A-Za-z])([0-9])/g,\"$1 $2\").replace(/([0-9])([A-Za-z])/g,\"$1 $2\").split(/[\\s,]+/).reduce(function(a,b){return b.match(/[A-Za-z]/)&&a.push([]),a[a.length-1].push(b),a},[]);\"Z\"===b[b.length-1][0].toUpperCase()&&b.pop();var d=b.map(function(a){var b=a.shift(),d=u[b.toLowerCase()];return c.extend({command:b},d.reduce(function(b,c,d){return b[c]=+a[d],b},{}))}),e=[this.pos,0];return Array.prototype.push.apply(e,d),Array.prototype.splice.apply(this.pathElements,e),this.pos+=d.length,this}function n(){var a=Math.pow(10,this.options.accuracy);return this.pathElements.reduce(function(b,c){var d=u[c.command.toLowerCase()].map(function(b){return this.options.accuracy?Math.round(c[b]*a)/a:c[b]}.bind(this));return b+c.command+d.join(\",\")}.bind(this),\"\")+(this.close?\"Z\":\"\")}function o(a,b){return e(this.pathElements,function(c,d){c[d]*=\"x\"===d[0]?a:b}),this}function p(a,b){return e(this.pathElements,function(c,d){c[d]+=\"x\"===d[0]?a:b}),this}function q(a){return e(this.pathElements,function(b,c,d,e,f){var g=a(b,c,d,e,f);(g||0===g)&&(b[c]=g)}),this}function r(a){var b=new c.Svg.Path(a||this.close);return b.pos=this.pos,b.pathElements=this.pathElements.slice().map(function(a){return c.extend({},a)}),b.options=c.extend({},this.options),b}function s(a){var b=[new c.Svg.Path];return this.pathElements.forEach(function(d){d.command===a.toUpperCase()&&0!==b[b.length-1].pathElements.length&&b.push(new c.Svg.Path),b[b.length-1].pathElements.push(d)}),b}function t(a,b,d){for(var e=new c.Svg.Path(b,d),f=0;f<a.length;f++)for(var g=a[f],h=0;h<g.pathElements.length;h++)e.pathElements.push(g.pathElements[h]);return e}var u={m:[\"x\",\"y\"],l:[\"x\",\"y\"],c:[\"x1\",\"y1\",\"x2\",\"y2\",\"x\",\"y\"],a:[\"rx\",\"ry\",\"xAr\",\"lAf\",\"sf\",\"x\",\"y\"]},v={accuracy:3};c.Svg.Path=c.Class.extend({constructor:f,position:g,remove:h,move:i,line:j,curve:k,arc:l,scale:o,translate:p,transform:q,parse:m,stringify:n,clone:r,splitByCommand:s}),c.Svg.Path.elementDescriptions=u,c.Svg.Path.join=t}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,c,d){this.units=a,this.counterUnits=a===f.x?f.y:f.x,this.chartRect=b,this.axisLength=b[a.rectEnd]-b[a.rectStart],this.gridOffset=b[a.rectOffset],this.ticks=c,this.options=d}function e(a,b,d,e,f){var g=e[\"axis\"+this.units.pos.toUpperCase()],h=this.ticks.map(this.projectValue.bind(this)),i=this.ticks.map(g.labelInterpolationFnc);h.forEach(function(j,k){var l,m={x:0,y:0};l=h[k+1]?h[k+1]-j:Math.max(this.axisLength-j,30),c.isFalseyButZero(i[k])&&\"\"!==i[k]||(\"x\"===this.units.pos?(j=this.chartRect.x1+j,m.x=e.axisX.labelOffset.x,\"start\"===e.axisX.position?m.y=this.chartRect.padding.top+e.axisX.labelOffset.y+(d?5:20):m.y=this.chartRect.y1+e.axisX.labelOffset.y+(d?5:20)):(j=this.chartRect.y1-j,m.y=e.axisY.labelOffset.y-(d?l:0),\"start\"===e.axisY.position?m.x=d?this.chartRect.padding.left+e.axisY.labelOffset.x:this.chartRect.x1-10:m.x=this.chartRect.x2+e.axisY.labelOffset.x+10),g.showGrid&&c.createGrid(j,k,this,this.gridOffset,this.chartRect[this.counterUnits.len](),a,[e.classNames.grid,e.classNames[this.units.dir]],f),g.showLabel&&c.createLabel(j,l,k,i,this,g.offset,m,b,[e.classNames.label,e.classNames[this.units.dir],\"start\"===g.position?e.classNames[g.position]:e.classNames.end],d,f))}.bind(this))}var f={x:{pos:\"x\",len:\"width\",dir:\"horizontal\",rectStart:\"x1\",rectEnd:\"x2\",rectOffset:\"y2\"},y:{pos:\"y\",len:\"height\",dir:\"vertical\",rectStart:\"y2\",rectEnd:\"y1\",rectOffset:\"x1\"}};c.Axis=c.Class.extend({constructor:d,createGridAndLabels:e,projectValue:function(a,b,c){throw new Error(\"Base axis can't be instantiated!\")}}),c.Axis.units=f}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,d,e){var f=e.highLow||c.getHighLow(b,e,a.pos);this.bounds=c.getBounds(d[a.rectEnd]-d[a.rectStart],f,e.scaleMinSpace||20,e.onlyInteger),this.range={min:this.bounds.min,max:this.bounds.max},c.AutoScaleAxis[\"super\"].constructor.call(this,a,d,this.bounds.values,e)}function e(a){return this.axisLength*(+c.getMultiValue(a,this.units.pos)-this.bounds.min)/this.bounds.range}c.AutoScaleAxis=c.Axis.extend({constructor:d,projectValue:e})}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,d,e){var f=e.highLow||c.getHighLow(b,e,a.pos);this.divisor=e.divisor||1,this.ticks=e.ticks||c.times(this.divisor).map(function(a,b){return f.low+(f.high-f.low)/this.divisor*b}.bind(this)),this.ticks.sort(function(a,b){return a-b}),this.range={min:f.low,max:f.high},c.FixedScaleAxis[\"super\"].constructor.call(this,a,d,this.ticks,e),this.stepLength=this.axisLength/this.divisor}function e(a){return this.axisLength*(+c.getMultiValue(a,this.units.pos)-this.range.min)/(this.range.max-this.range.min)}c.FixedScaleAxis=c.Axis.extend({constructor:d,projectValue:e})}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,d,e){c.StepAxis[\"super\"].constructor.call(this,a,d,e.ticks,e);var f=Math.max(1,e.ticks.length-(e.stretch?1:0));this.stepLength=this.axisLength/f}function e(a,b){return this.stepLength*b}c.StepAxis=c.Axis.extend({constructor:d,projectValue:e})}(window,document,a),function(a,b,c){\"use strict\";function d(a){var b=c.normalizeData(this.data,a.reverseData,!0);this.svg=c.createSvg(this.container,a.width,a.height,a.classNames.chart);var d,e,g=this.svg.elem(\"g\").addClass(a.classNames.gridGroup),h=this.svg.elem(\"g\"),i=this.svg.elem(\"g\").addClass(a.classNames.labelGroup),j=c.createChartRect(this.svg,a,f.padding);d=void 0===a.axisX.type?new c.StepAxis(c.Axis.units.x,b.normalized.series,j,c.extend({},a.axisX,{ticks:b.normalized.labels,stretch:a.fullWidth})):a.axisX.type.call(c,c.Axis.units.x,b.normalized.series,j,a.axisX),e=void 0===a.axisY.type?new c.AutoScaleAxis(c.Axis.units.y,b.normalized.series,j,c.extend({},a.axisY,{high:c.isNumeric(a.high)?a.high:a.axisY.high,low:c.isNumeric(a.low)?a.low:a.axisY.low})):a.axisY.type.call(c,c.Axis.units.y,b.normalized.series,j,a.axisY),d.createGridAndLabels(g,i,this.supportsForeignObject,a,this.eventEmitter),e.createGridAndLabels(g,i,this.supportsForeignObject,a,this.eventEmitter),a.showGridBackground&&c.createGridBackground(g,j,a.classNames.gridBackground,this.eventEmitter),b.raw.series.forEach(function(f,g){var i=h.elem(\"g\");i.attr({\"ct:series-name\":f.name,\"ct:meta\":c.serialize(f.meta)}),i.addClass([a.classNames.series,f.className||a.classNames.series+\"-\"+c.alphaNumerate(g)].join(\" \"));var k=[],l=[];b.normalized.series[g].forEach(function(a,h){var i={x:j.x1+d.projectValue(a,h,b.normalized.series[g]),y:j.y1-e.projectValue(a,h,b.normalized.series[g])};k.push(i.x,i.y),l.push({value:a,valueIndex:h,meta:c.getMetaData(f,h)})}.bind(this));var m={lineSmooth:c.getSeriesOption(f,a,\"lineSmooth\"),showPoint:c.getSeriesOption(f,a,\"showPoint\"),showLine:c.getSeriesOption(f,a,\"showLine\"),showArea:c.getSeriesOption(f,a,\"showArea\"),areaBase:c.getSeriesOption(f,a,\"areaBase\")},n=\"function\"==typeof m.lineSmooth?m.lineSmooth:m.lineSmooth?c.Interpolation.monotoneCubic():c.Interpolation.none(),o=n(k,l);if(m.showPoint&&o.pathElements.forEach(function(b){var h=i.elem(\"line\",{x1:b.x,y1:b.y,x2:b.x+.01,y2:b.y},a.classNames.point).attr({\"ct:value\":[b.data.value.x,b.data.value.y].filter(c.isNumeric).join(\",\"),\"ct:meta\":c.serialize(b.data.meta)});this.eventEmitter.emit(\"draw\",{type:\"point\",value:b.data.value,index:b.data.valueIndex,meta:b.data.meta,series:f,seriesIndex:g,axisX:d,axisY:e,group:i,element:h,x:b.x,y:b.y})}.bind(this)),m.showLine){var p=i.elem(\"path\",{d:o.stringify()},a.classNames.line,!0);this.eventEmitter.emit(\"draw\",{type:\"line\",values:b.normalized.series[g],path:o.clone(),chartRect:j,index:g,series:f,seriesIndex:g,seriesMeta:f.meta,axisX:d,axisY:e,group:i,element:p})}if(m.showArea&&e.range){var q=Math.max(Math.min(m.areaBase,e.range.max),e.range.min),r=j.y1-e.projectValue(q);o.splitByCommand(\"M\").filter(function(a){return a.pathElements.length>1}).map(function(a){var b=a.pathElements[0],c=a.pathElements[a.pathElements.length-1];return a.clone(!0).position(0).remove(1).move(b.x,r).line(b.x,b.y).position(a.pathElements.length+1).line(c.x,r)}).forEach(function(c){var h=i.elem(\"path\",{d:c.stringify()},a.classNames.area,!0);this.eventEmitter.emit(\"draw\",{type:\"area\",values:b.normalized.series[g],path:c.clone(),series:f,seriesIndex:g,axisX:d,axisY:e,chartRect:j,index:g,group:i,element:h})}.bind(this))}}.bind(this)),this.eventEmitter.emit(\"created\",{bounds:e.bounds,chartRect:j,axisX:d,axisY:e,svg:this.svg,options:a})}function e(a,b,d,e){c.Line[\"super\"].constructor.call(this,a,b,f,c.extend({},f,d),e)}var f={axisX:{offset:30,position:\"end\",labelOffset:{x:0,y:0},showLabel:!0,showGrid:!0,labelInterpolationFnc:c.noop,type:void 0},axisY:{offset:40,position:\"start\",labelOffset:{x:0,y:0},showLabel:!0,showGrid:!0,labelInterpolationFnc:c.noop,type:void 0,scaleMinSpace:20,onlyInteger:!1},width:void 0,height:void 0,showLine:!0,showPoint:!0,showArea:!1,areaBase:0,lineSmooth:!0,showGridBackground:!1,low:void 0,high:void 0,chartPadding:{top:15,right:15,bottom:5,left:10},fullWidth:!1,reverseData:!1,classNames:{chart:\"ct-chart-line\",label:\"ct-label\",labelGroup:\"ct-labels\",series:\"ct-series\",line:\"ct-line\",point:\"ct-point\",area:\"ct-area\",grid:\"ct-grid\",gridGroup:\"ct-grids\",gridBackground:\"ct-grid-background\",vertical:\"ct-vertical\",horizontal:\"ct-horizontal\",start:\"ct-start\",end:\"ct-end\"}};c.Line=c.Base.extend({constructor:e,createChart:d})}(window,document,a),function(a,b,c){\"use strict\";function d(a){var b,d;a.distributeSeries?(b=c.normalizeData(this.data,a.reverseData,a.horizontalBars?\"x\":\"y\"),b.normalized.series=b.normalized.series.map(function(a){return[a]})):b=c.normalizeData(this.data,a.reverseData,a.horizontalBars?\"x\":\"y\"),this.svg=c.createSvg(this.container,a.width,a.height,a.classNames.chart+(a.horizontalBars?\" \"+a.classNames.horizontalBars:\"\"));var e=this.svg.elem(\"g\").addClass(a.classNames.gridGroup),g=this.svg.elem(\"g\"),h=this.svg.elem(\"g\").addClass(a.classNames.labelGroup);if(a.stackBars&&0!==b.normalized.series.length){var i=c.serialMap(b.normalized.series,function(){return Array.prototype.slice.call(arguments).map(function(a){return a}).reduce(function(a,b){return{x:a.x+(b&&b.x)||0,y:a.y+(b&&b.y)||0}},{x:0,y:0})});d=c.getHighLow([i],a,a.horizontalBars?\"x\":\"y\")}else d=c.getHighLow(b.normalized.series,a,a.horizontalBars?\"x\":\"y\");d.high=+a.high||(0===a.high?0:d.high),d.low=+a.low||(0===a.low?0:d.low);var j,k,l,m,n,o=c.createChartRect(this.svg,a,f.padding);k=a.distributeSeries&&a.stackBars?b.normalized.labels.slice(0,1):b.normalized.labels,a.horizontalBars?(j=m=void 0===a.axisX.type?new c.AutoScaleAxis(c.Axis.units.x,b.normalized.series,o,c.extend({},a.axisX,{highLow:d,referenceValue:0})):a.axisX.type.call(c,c.Axis.units.x,b.normalized.series,o,c.extend({},a.axisX,{highLow:d,referenceValue:0})),l=n=void 0===a.axisY.type?new c.StepAxis(c.Axis.units.y,b.normalized.series,o,{ticks:k}):a.axisY.type.call(c,c.Axis.units.y,b.normalized.series,o,a.axisY)):(l=m=void 0===a.axisX.type?new c.StepAxis(c.Axis.units.x,b.normalized.series,o,{ticks:k}):a.axisX.type.call(c,c.Axis.units.x,b.normalized.series,o,a.axisX),j=n=void 0===a.axisY.type?new c.AutoScaleAxis(c.Axis.units.y,b.normalized.series,o,c.extend({},a.axisY,{highLow:d,referenceValue:0})):a.axisY.type.call(c,c.Axis.units.y,b.normalized.series,o,c.extend({},a.axisY,{highLow:d,referenceValue:0})));var p=a.horizontalBars?o.x1+j.projectValue(0):o.y1-j.projectValue(0),q=[];l.createGridAndLabels(e,h,this.supportsForeignObject,a,this.eventEmitter),j.createGridAndLabels(e,h,this.supportsForeignObject,a,this.eventEmitter),a.showGridBackground&&c.createGridBackground(e,o,a.classNames.gridBackground,this.eventEmitter),b.raw.series.forEach(function(d,e){var f,h,i=e-(b.raw.series.length-1)/2;f=a.distributeSeries&&!a.stackBars?l.axisLength/b.normalized.series.length/2:a.distributeSeries&&a.stackBars?l.axisLength/2:l.axisLength/b.normalized.series[e].length/2,h=g.elem(\"g\"),h.attr({\"ct:series-name\":d.name,\"ct:meta\":c.serialize(d.meta)}),h.addClass([a.classNames.series,d.className||a.classNames.series+\"-\"+c.alphaNumerate(e)].join(\" \")),b.normalized.series[e].forEach(function(g,k){var r,s,t,u;if(u=a.distributeSeries&&!a.stackBars?e:a.distributeSeries&&a.stackBars?0:k,r=a.horizontalBars?{x:o.x1+j.projectValue(g&&g.x?g.x:0,k,b.normalized.series[e]),y:o.y1-l.projectValue(g&&g.y?g.y:0,u,b.normalized.series[e])}:{x:o.x1+l.projectValue(g&&g.x?g.x:0,u,b.normalized.series[e]),y:o.y1-j.projectValue(g&&g.y?g.y:0,k,b.normalized.series[e])},l instanceof c.StepAxis&&(l.options.stretch||(r[l.units.pos]+=f*(a.horizontalBars?-1:1)),r[l.units.pos]+=a.stackBars||a.distributeSeries?0:i*a.seriesBarDistance*(a.horizontalBars?-1:1)),t=q[k]||p,q[k]=t-(p-r[l.counterUnits.pos]),void 0!==g){var v={};v[l.units.pos+\"1\"]=r[l.units.pos],v[l.units.pos+\"2\"]=r[l.units.pos],!a.stackBars||\"accumulate\"!==a.stackMode&&a.stackMode?(v[l.counterUnits.pos+\"1\"]=p,v[l.counterUnits.pos+\"2\"]=r[l.counterUnits.pos]):(v[l.counterUnits.pos+\"1\"]=t,v[l.counterUnits.pos+\"2\"]=q[k]),v.x1=Math.min(Math.max(v.x1,o.x1),o.x2),v.x2=Math.min(Math.max(v.x2,o.x1),o.x2),v.y1=Math.min(Math.max(v.y1,o.y2),o.y1),v.y2=Math.min(Math.max(v.y2,o.y2),o.y1);var w=c.getMetaData(d,k);s=h.elem(\"line\",v,a.classNames.bar).attr({\"ct:value\":[g.x,g.y].filter(c.isNumeric).join(\",\"),\"ct:meta\":c.serialize(w)}),this.eventEmitter.emit(\"draw\",c.extend({type:\"bar\",value:g,index:k,meta:w,series:d,seriesIndex:e,axisX:m,axisY:n,chartRect:o,group:h,element:s},v))}}.bind(this))}.bind(this)),this.eventEmitter.emit(\"created\",{bounds:j.bounds,chartRect:o,axisX:m,axisY:n,svg:this.svg,options:a})}function e(a,b,d,e){c.Bar[\"super\"].constructor.call(this,a,b,f,c.extend({},f,d),e)}var f={axisX:{offset:30,position:\"end\",labelOffset:{x:0,y:0},showLabel:!0,showGrid:!0,labelInterpolationFnc:c.noop,scaleMinSpace:30,onlyInteger:!1},axisY:{offset:40,position:\"start\",labelOffset:{x:0,y:0},showLabel:!0,showGrid:!0,labelInterpolationFnc:c.noop,scaleMinSpace:20,onlyInteger:!1},width:void 0,height:void 0,high:void 0,low:void 0,referenceValue:0,chartPadding:{top:15,right:15,bottom:5,left:10},seriesBarDistance:15,stackBars:!1,stackMode:\"accumulate\",horizontalBars:!1,distributeSeries:!1,reverseData:!1,showGridBackground:!1,classNames:{chart:\"ct-chart-bar\",horizontalBars:\"ct-horizontal-bars\",label:\"ct-label\",labelGroup:\"ct-labels\",series:\"ct-series\",bar:\"ct-bar\",grid:\"ct-grid\",gridGroup:\"ct-grids\",gridBackground:\"ct-grid-background\",vertical:\"ct-vertical\",horizontal:\"ct-horizontal\",start:\"ct-start\",end:\"ct-end\"}};c.Bar=c.Base.extend({constructor:e,createChart:d})}(window,document,a),function(a,b,c){\"use strict\";function d(a,b,c){var d=b.x>a.x;return d&&\"explode\"===c||!d&&\"implode\"===c?\"start\":d&&\"implode\"===c||!d&&\"explode\"===c?\"end\":\"middle\"}function e(a){var b,e,f,h,i,j=c.normalizeData(this.data),k=[],l=a.startAngle;this.svg=c.createSvg(this.container,a.width,a.height,a.donut?a.classNames.chartDonut:a.classNames.chartPie),e=c.createChartRect(this.svg,a,g.padding),f=Math.min(e.width()/2,e.height()/2),i=a.total||j.normalized.series.reduce(function(a,b){return a+b},0);var m=c.quantity(a.donutWidth);\"%\"===m.unit&&(m.value*=f/100),f-=a.donut?m.value/2:0,h=\"outside\"===a.labelPosition||a.donut?f:\"center\"===a.labelPosition?0:f/2,h+=a.labelOffset;var n={x:e.x1+e.width()/2,y:e.y2+e.height()/2},o=1===j.raw.series.filter(function(a){return a.hasOwnProperty(\"value\")?0!==a.value:0!==a}).length;j.raw.series.forEach(function(a,b){k[b]=this.svg.elem(\"g\",null,null)}.bind(this)),a.showLabel&&(b=this.svg.elem(\"g\",null,null)),j.raw.series.forEach(function(e,g){if(0!==j.normalized.series[g]||!a.ignoreEmptyValues){k[g].attr({\"ct:series-name\":e.name}),k[g].addClass([a.classNames.series,e.className||a.classNames.series+\"-\"+c.alphaNumerate(g)].join(\" \"));var p=i>0?l+j.normalized.series[g]/i*360:0,q=Math.max(0,l-(0===g||o?0:.2));p-q>=359.99&&(p=q+359.99);var r=c.polarToCartesian(n.x,n.y,f,q),s=c.polarToCartesian(n.x,n.y,f,p),t=new c.Svg.Path((!a.donut)).move(s.x,s.y).arc(f,f,0,p-l>180,0,r.x,r.y);a.donut||t.line(n.x,n.y);var u=k[g].elem(\"path\",{d:t.stringify()},a.donut?a.classNames.sliceDonut:a.classNames.slicePie);if(u.attr({\"ct:value\":j.normalized.series[g],\"ct:meta\":c.serialize(e.meta)}),a.donut&&u.attr({style:\"stroke-width: \"+m.value+\"px\"}),this.eventEmitter.emit(\"draw\",{type:\"slice\",value:j.normalized.series[g],totalDataSum:i,index:g,meta:e.meta,series:e,group:k[g],element:u,path:t.clone(),center:n,radius:f,startAngle:l,endAngle:p}),a.showLabel){var v;v=1===j.raw.series.length?{x:n.x,y:n.y}:c.polarToCartesian(n.x,n.y,h,l+(p-l)/2);var w;w=j.normalized.labels&&!c.isFalseyButZero(j.normalized.labels[g])?j.normalized.labels[g]:j.normalized.series[g];var x=a.labelInterpolationFnc(w,g);if(x||0===x){var y=b.elem(\"text\",{dx:v.x,dy:v.y,\"text-anchor\":d(n,v,a.labelDirection)},a.classNames.label).text(\"\"+x);this.eventEmitter.emit(\"draw\",{type:\"label\",index:g,group:b,element:y,text:\"\"+x,x:v.x,y:v.y})}}l=p}}.bind(this)),this.eventEmitter.emit(\"created\",{chartRect:e,svg:this.svg,options:a})}function f(a,b,d,e){c.Pie[\"super\"].constructor.call(this,a,b,g,c.extend({},g,d),e)}var g={width:void 0,height:void 0,chartPadding:5,classNames:{chartPie:\"ct-chart-pie\",chartDonut:\"ct-chart-donut\",series:\"ct-series\",slicePie:\"ct-slice-pie\",sliceDonut:\"ct-slice-donut\",label:\"ct-label\"},startAngle:0,total:void 0,donut:!1,donutWidth:60,showLabel:!0,labelOffset:0,labelPosition:\"inside\",labelInterpolationFnc:c.noop,labelDirection:\"neutral\",reverseData:!1,ignoreEmptyValues:!1};c.Pie=c.Base.extend({constructor:f,createChart:e,determineAnchorPosition:d})}(window,document,a),a});\n";
    }

    inline std::string get_second_half() {
        return "/*\n"
                "* Souffle - A Datalog Compiler\n"
                "* Copyright (c) 2017, The Souffle Developers. All rights reserved\n"
                "* Licensed under the Universal Permissive License v 1.0 as shown at:\n"
                "* - https://opensource.org/licenses/UPL\n"
                "* - <souffle root>/licenses/SOUFFLE-UPL.txt\n"
                "*/\n"
                "\n"
                "(function () {\n"
                "    var a = function (a) {\n"
                "        return a;\n"
                "    }, b = function (a, b) {\n"
                "        return a = parseFloat(a), b = parseFloat(b), a = isNaN(a) ? 0 : a, b = isNaN(b) ? 0 : b, a - b\n"
                "    };\n"
                "    Tablesort.extend(\"number\", function (a) {\n"
                "        return a.match(/.*/)\n"
                "    }, function (c, d) {\n"
                "        return c = a(c), d = a(d), b(d, c)\n"
                "    })\n"
                "})();\n"
                "\n"
                "(function () {\n"
                "    var b = function (a, b) {\n"
                "        return a.localeCompare(b);\n"
                "    };\n"
                "    Tablesort.extend(\"text\", function (a) {\n"
                "        return a.match(/.*/)\n"
                "    }, function (c, d) {\n"
                "        return b(d, c)\n"
                "    })\n"
                "})();\n"
                "\n"
                "(function () {\n"
                "    var cleanNumber = function (x) {\n"
                "            if (x.slice(-1) == 'Y') {\n"
                "                return parseFloat(x.slice(0, -1)) * 365 * 24 * 60 * 60;\n"
                "            } else if (x.slice(-1) == 'W') {\n"
                "                return parseFloat(x.slice(0, -1)) * 7 * 24 * 60 * 60;\n"
                "            } else if (x.slice(-1) == \"D\") {\n"
                "                return parseFloat(x.slice(0, -1)) * 24 * 60 * 60;\n"
                "            } else if (x.slice(-1) == \"H\") {\n"
                "                return parseFloat(x.slice(0, -1)) * 60 * 60;\n"
                "            } else if (x.slice(-1) == \"m\") {\n"
                "                return parseFloat(x.slice(0, -1)) * 60;\n"
                "            } else if (x.slice(-2) == \"µs\") {\n"
                "                return parseFloat(x.slice(0, -2)) / 1000000;\n"
                "            } else if (x.slice(-1) == \"s\") {\n"
                "                return parseFloat(x.slice(0, -1));\n"
                "            }\n"
                "            return parseFloat(x);\n"
                "        },\n"
                "        compareNumber = function (a, b) {\n"
                "            a = isNaN(a) ? 0 : a;\n"
                "            b = isNaN(b) ? 0 : b;\n"
                "            return a - b;\n"
                "        };\n"
                "    Tablesort.extend('time', function (item) {\n"
                "        return true;\n"
                "    }, function (a, b) {\n"
                "        a = cleanNumber(a);\n"
                "        b = cleanNumber(b);\n"
                "        return compareNumber(b, a);\n"
                "    });\n"
                "}());\n"
                "\n"
                "\n"
                "function select_for_graph(a) {\n"
                "    for (tabcontent = document.getElementById(\"tabcontent\"), tablinks = document.getElementsByClassName(\"rul_ver_row\"), i = 0; i < tablinks.length; i++) tablinks[i].style.background = \"rgba(255,255,0,0)\";\n"
                "    for (tablinks = document.getElementsByClassName(\"rulesofrel_row\"), i = 0; i < tablinks.length; i++) tablinks[i].style.background = \"rgba(255,255,0,0)\";\n"
                "    a.style.background = \"rgba(255,255,0,0.2)\", selected_for_chart = a\n"
                "}\n"
                "\n"
                "function showChart() {\n"
                "    var a, b, c, d, j;\n"
                "    if (!selected_for_chart) return void alert(\"please select a recursive rule to graph\");\n"
                "    if (a = selected_for_chart.cells[1].innerHTML, \"C\" != a[0]) return void alert(\"Please select a recursive rule (ID starts with C)\");\n"
                "    for (document.getElementById(\"chart_tab\").style.display = \"block\", c = document.getElementsByClassName(\"tabcontent\"), b = 0; b < c.length; b++) c[b].style.display = \"none\";\n"
                "    for (d = document.getElementsByClassName(\"tablinks\"), b = 0; b < d.length; b++) d[b].className = d[b].className.replace(\" active\", \"\");\n"
                "    document.getElementById(\"chart_tab\").style.display = \"block\", document.getElementById(\"chart_tab\").className += \" active\", document.getElementById(\"chart\").style.display = \"block\";\n"
                "    var e = [],\n"
                "        f = [],\n"
                "        g = [];\n"
                "    for (j = 0; j < data.rul[a][10].tot_t.length; j++) e.push(j.toString()), f.push({\n"
                "        value: data.rul[a][10].tot_t[j]\n"
                "    }), g.push({\n"
                "        value: data.rul[a][10].tuples[j]\n"
                "    });\n"
                "    draw_graph(e, f, g)\n"
                "}\n"
                "\n"
                "function ctBarLabels(a) {\n"
                "    a instanceof Chartist.Bar && a.on(\"draw\", function (a) {\n"
                "        var b, c, d, e;\n"
                "        if (\"bar\" === a.type && (b = a.x1 + .5 * a.element.width(), c = a.y1 + a.element.height() * -1 - 2, e = a.element.attr(\"ct:value\"), \"0\" !== e)) return d = new Chartist.Svg(\"text\"), d.text(e), d.addClass(\"ct-barlabel\"), d.attr({\n"
                "            x: b,\n"
                "            y: c,\n"
                "            \"text-anchor\": \"middle\"\n"
                "        }), a.group.append(d)\n"
                "    })\n"
                "}\n"
                "\n"
                "function draw_graph(a, b, c) {\n"
                "    var d = {\n"
                "        height: \"37vh\"\n"
                "    };\n"
                "    show_graph_vals && (d.plugins = [ctBarLabels]), new Chartist.Bar(\".ct-chart1\", {\n"
                "        labels: a,\n"
                "        series: [b]\n"
                "    }, d), new Chartist.Bar(\".ct-chart2\", {\n"
                "        labels: a,\n"
                "        series: [c]\n"
                "    }, d)\n"
                "}\n"
                "\n"
                "function clean_percentages(data) {\n"
                "    if (data < 1) {\n"
                "        return data.toFixed(3);\n"
                "    }\n"
                "    return data.toPrecision(3);\n"
                "}\n"
                "\n"
                "function humanize_time(data) {\n"
                "    if (precision) return data;\n"
                "    if (data < 1) {\n"
                "        milli = data * 1000;\n"
                "        if (milli > 1) {\n"
                "            return data.toFixed(3) + \"s\"\n"
                "        }\n"
                "        micro = milli * 1000;\n"
                "        if (micro >= 1) {\n"
                "            return micro.toPrecision(3) + \"µs\"\n"
                "        }\n"
                "        return micro + \"µs\"\n"
                "    } else {\n"
                "        minutes = (data / 60);\n"
                "        if (minutes < 3) return data.toPrecision(3) + \"s\";\n"
                "        hours = (minutes / 60);\n"
                "        if (hours < 3) return minutes.toFixed(1) + \"m\";\n"
                "        days = (hours / 24);\n"
                "        if (days < 3) return hours.toFixed(1) + \"H\";\n"
                "        weeks = (days / 7);\n"
                "        if (weeks < 3) return days.toFixed(1) + \"D\";\n"
                "        year = (days / 365);\n"
                "        if (year < 3) return weeks.toFixed(1) + \"W\";\n"
                "        return year.toFixed(1) + \"Y\"\n"
                "    }\n"
                "}\n"
                "\n"
                "function minify_numbers(data) {\n"
                "    if (precision) return data;\n"
                "    if (data < 1e6) return data;\n"
                "    return data.toExponential(2);\n"
                "}\n"
                "\n"
                "function changeRowRel(a) {\n"
                "    selected_for_chart = !1;\n"
                "    selected.rel = a;\n"
                "    var b, c, d, e, f, g, h;\n"
                "    for (d = document.getElementsByClassName(\"rel_row\"), b = 0; b < d.length; b++) d[b].style.background = \"rgba(255,255,0,0)\";\n"
                "    document.getElementById(a).style.background = \"rgba(255,255,0,0.2)\", document.getElementById(\"rulesofrel\").style.display = \"block\", c = document.getElementById(\"rulesofrel_body\"), c.innerHTML = \"\", e = data.rel[a],\n"
                "             f = document.createElement(\"tr\"),\n"
                "\n"
                "        h = document.createElement(\"td\"),\n"
                "        h.innerHTML = e[0],\n"
                "        f.appendChild(h);\n"
                "    h = document.createElement(\"td\"),\n"
                "        h.innerHTML = e[1],\n"
                "        f.appendChild(h);\n"
                "    h = document.createElement(\"td\"),\n"
                "        h.innerHTML = humanize_time(e[2]),\n"
                "        f.appendChild(h);\n"
                "    h = document.createElement(\"td\"),\n"
                "        h.innerHTML = humanize_time(e[3]),\n"
                "        f.appendChild(h);\n"
                "    h = document.createElement(\"td\"),\n"
                "        h.innerHTML = humanize_time(e[4]),\n"
                "        f.appendChild(h);\n"
                "    h = document.createElement(\"td\"),\n"
                "        h.innerHTML = humanize_time(e[5]),\n"
                "        f.appendChild(h);\n"
                "    h = document.createElement(\"td\"),\n"
                "        h.innerHTML = minify_numbers(e[6]),\n"
                "        f.appendChild(h);\n"
                "    for (h = document.createElement(\"td\"), g = document.createElement(\"div\"), g.className = \"perc_time\", g.style.width = \"100%\", g.innerHTML = \"100\", h.appendChild(g), f.appendChild(h), h = document.createElement(\"td\"), g = document.createElement(\"div\"), g.className = \"perc_time\", g.style.width = \"100%\", g.innerHTML = \"100\", h.appendChild(g), f.appendChild(h), h = document.createElement(\"td\"), h.innerHTML = e[7], f.appendChild(h), f.className = \"rulesofrel_row\", f.onclick = function () {\n"
                "        select_for_graph(this)\n"
                "    }, c.appendChild(f), b = 0; b < e[8].length; b++) {\n"
                "        f = document.createElement(\"tr\");\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = data.rul[e[8][b]][0],\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = data.rul[e[8][b]][1],\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = humanize_time(data.rul[e[8][b]][2]),\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = humanize_time(data.rul[e[8][b]][3]),\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = humanize_time(data.rul[e[8][b]][4]),\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = humanize_time(data.rul[e[8][b]][5]),\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            h.innerHTML = minify_numbers(data.rul[e[8][b]][6]),\n"
                "            f.appendChild(h);\n"
                "        h = document.createElement(\"td\"),\n"
                "            g = document.createElement(\"div\"),\n"
                "            g.className = \"perc_time\",\n"
                "            0 == e[2] ? (g.style.width = \"0%\", g.innerHTML = \"0\") : (\n"
                "                    g.style.width = 100 * data.rul[e[8][b]][2] / e[2] + \"%\",\n"
                "                    g.innerHTML = (100 * data.rul[e[8][b]][2] / e[2]).toPrecision(4)\n"
                "                ),\n"
                "            h.appendChild(g),\n"
                "            f.appendChild(h),\n"
                "            h = document.createElement(\"td\"),\n"
                "            g = document.createElement(\"div\"),\n"
                "            g.className = \"perc_time\", 0 == e[6] ? (g.style.width = \"0%\", g.innerHTML = \"0\") : (\n"
                "                g.style.width = 100 * data.rul[e[8][b]][6] / e[6] + \"%\",\n"
                "                g.innerHTML = (100 * data.rul[e[8][b]][6] / e[6]).toPrecision(4)\n"
                "            ),\n"
                "            h.appendChild(g), f.appendChild(h), h = document.createElement(\"td\"),\n"
                "            h.innerHTML = data.rul[e[8][b]][7],\n"
                "            f.appendChild(h),\n"
                "            f.onclick = function () {\n"
                "            select_for_graph(this)\n"
                "        }, f.className = \"rulesofrel_row\",\n"
                "            c.appendChild(f)\n"
                "    }\n"
                "    created_relrul || (new Tablesort(document.getElementById(\"rulesofrel_table\")), created_relrul = !0)\n"
                "}\n"
                "\n"
                "function changeRowRul(a) {\n"
                "    selected_for_chart = !1;\n"
                "    selected.rul = a;\n"
                "\n"
                "    var b, c, d, e, f, g, h;\n"
                "    for (d = document.getElementsByClassName(\"rul_row\"), b = 0; b < d.length; b++) d[b].style.background = \"rgba(255,255,0,0)\";\n"
                "    document.getElementById(a).style.background = \"rgba(255,255,0,0.2)\",\n"
                "        document.getElementById(\"rulver\").style.display = \"block\",\n"
                "        c = document.getElementById(\"rulver_body\"), c.innerHTML = \"\",\n"
                "        e = data.rul[a], f = document.createElement(\"tr\"),\n"
                "        g = document.createElement(\"td\"),\n"
                "        g.innerHTML = e[0],\n"
                "        f.appendChild(g);\n"
                "    g = document.createElement(\"td\"),\n"
                "        g.innerHTML = e[1],\n"
                "        f.appendChild(g);\n"
                "    g = document.createElement(\"td\"),\n"
                "        g.innerHTML = humanize_time(e[2]),\n"
                "        f.appendChild(g);\n"
                "    g = document.createElement(\"td\"),\n"
                "        g.innerHTML = humanize_time(e[3]),\n"
                "        f.appendChild(g);\n"
                "    g = document.createElement(\"td\"),\n"
                "        g.innerHTML = humanize_time(e[4]),\n"
                "        f.appendChild(g);\n"
                "    g = document.createElement(\"td\"),\n"
                "        g.innerHTML = humanize_time(e[5]),\n"
                "        f.appendChild(g);\n"
                "    g = document.createElement(\"td\"),\n"
                "        g.innerHTML = minify_numbers(e[6]),\n"
                "        f.appendChild(g);\n"
                "    for (g = document.createElement(\"td\"), g.innerHTML = \"-\", f.appendChild(g), g = document.createElement(\"td\"), h = document.createElement(\"div\"), h.className = \"perc_time\", h.style.width = \"100%\", h.innerHTML = \"100\", g.appendChild(h), f.appendChild(g), g = document.createElement(\"td\"), h = document.createElement(\"div\"), h.className = \"perc_time\", h.style.width = \"100%\", h.innerHTML = \"100\", g.appendChild(h), f.appendChild(g), g = document.createElement(\"td\"), g.innerHTML = e[7], f.appendChild(g), f.className = \"rul_ver_row\", f.onclick = function () {\n"
                "        select_for_graph(this)\n"
                "    }, c.appendChild(f), b = 0; b < e[8].length; b++) {\n"
                "        f = document.createElement(\"tr\");\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = data.rul[e[8][b][1]][0],\n"
                "            f.appendChild(g);\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = data.rul[e[8][b][1]][1],\n"
                "            f.appendChild(g);\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = humanize_time(data.rul[e[8][b][1]][2]),\n"
                "            f.appendChild(g);\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = humanize_time(data.rul[e[8][b][1]][3]),\n"
                "            f.appendChild(g);\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = humanize_time(data.rul[e[8][b][1]][4]),\n"
                "            f.appendChild(g);\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = humanize_time(data.rul[e[8][b][1]][5]),\n"
                "            f.appendChild(g);\n"
                "        g = document.createElement(\"td\"),\n"
                "            g.innerHTML = minify_numbers(data.rul[e[8][b][1]][6]),\n"
                "            f.appendChild(g);\n"
                "\n"
                "        g = document.createElement(\"td\"), g.innerHTML = e[8][b][0], f.appendChild(g), g = document.createElement(\"td\"), h = document.createElement(\"div\"), h.className = \"perc_time\", 0 == e[2] ? (h.style.width = \"0%\", h.innerHTML = \"0\") : (h.style.width = 100 * data.rul[e[8][b][1]][2] / e[2] + \"%\", h.innerHTML = (100 * data.rul[e[8][b][1]][2] / e[2]).toPrecision(4)), g.appendChild(h), f.appendChild(g), g = document.createElement(\"td\"), h = document.createElement(\"div\"), h.className = \"perc_time\", 0 == e[6] ? (h.style.width = \"0%\", h.innerHTML = \"0\") : (h.style.width = 100 * data.rul[e[8][b][1]][6] / e[6] + \"%\", h.innerHTML = (100 * data.rul[e[8][b][1]][6] / e[6]).toPrecision(4)), g.appendChild(h), f.appendChild(g), g = document.createElement(\"td\"), g.innerHTML = data.rul[e[8][b][1]][7], f.appendChild(g), f.className = \"rul_ver_row\", f.onclick = function () {\n"
                "            select_for_graph(this)\n"
                "        }, c.appendChild(f)\n"
                "    }\n"
                "    created_rulver || (new Tablesort(document.getElementById(\"rulvertable\")), created_rulver = !0)\n"
                "}\n"
                "\n"
                "function changeTab(a, b) {\n"
                "    document.getElementById(\"chart_tab\").style.display = \"none\";\n"
                "    var c, d, e;\n"
                "    for (d = document.getElementsByClassName(\"tabcontent\"), c = 0; c < d.length; c++) d[c].style.display = \"none\";\n"
                "    for (e = document.getElementsByClassName(\"tablinks\"), c = 0; c < e.length; c++) e[c].className = e[c].className.replace(\" active\", \"\");\n"
                "    document.getElementById(b).style.display = \"block\", a.currentTarget.className += \" active\"\n"
                "}\n"
                "\n"
                "function gen_top() {\n"
                "    x = document.getElementById(\"Top\");\n"
                "    line1 = document.createElement(\"p\");\n"
                "    line1.textContent = \"Total runtime: \" + data.top[0],\n"
                "        line2 = document.createElement(\"p\"),\n"
                "        line2.textContent = \"Total tuples: \" + data.top[1],\n"
                "        x.appendChild(line1),\n"
                "        x.appendChild(line2)\n"
                "}\n"
                "\n"
                "function gen_rel_table() {\n"
                "    var a, b, c, d, f = 0,\n"
                "        g = .01;\n"
                "    for (d in data.rel) data.rel.hasOwnProperty(d) && !isNaN(data.rel[d][2])  && (f += data.rel[d][2], g += parseFloat(data.rel[d][6]));\n"
                "    a = document.getElementById(\"Rel_table_body\");\n"
                "    a.innerHTML=\"\";\n"
                "    for (d in data.rel)\n"
                "        if (data.rel.hasOwnProperty(d)) {\n"
                "            b = document.createElement(\"tr\"), b.id = data.rel[d][1], b.className = \"rel_row\", b.onclick = function () {\n"
                "                changeRowRel(this.id)\n"
                "            }, c = document.createElement(\"td\"),\n"
                "                c.innerHTML = data.rel[d][0],\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = data.rel[d][1],\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rel[d][2]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rel[d][3]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rel[d][4]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rel[d][5]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = minify_numbers(data.rel[d][6]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                div = document.createElement(\"div\"),\n"
                "                div.className = \"perc_time\",\n"
                "                div.style.width = data.rel[d][2] / f * 100 + \"%\",\n"
                "                div.innerHTML = clean_percentages(data.rel[d][2] / f * 100),\n"
                "                c.appendChild(div),\n"
                "                b.appendChild(c),\n"
                "                c = document.createElement(\"td\"),\n"
                "                div = document.createElement(\"div\"),\n"
                "                div.className = \"perc_time\",\n"
                "                div.style.width = 100 * parseFloat(data.rel[d][6]) / g + \"%\",\n"
                "                div.innerHTML = clean_percentages(100 * parseFloat(data.rel[d][6]) / g),\n"
                "                c.appendChild(div),\n"
                "                b.appendChild(c),\n"
                "                c = document.createElement(\"td\"),\n"
                "                c.innerHTML = data.rel[d][7],\n"
                "                b.appendChild(c),\n"
                "                a.appendChild(b)\n"
                "        }\n"
                "}\n"
                "\n"
                "function gen_rul_table() {\n"
                "    var a, b, c, d, f = 0,\n"
                "        g = .01;\n"
                "    for (d in data.rul) data.rul.hasOwnProperty(d) && !isNaN(data.rul[d][2]) && (f += data.rul[d][2], g += parseFloat(data.rul[d][6]));\n"
                "    a = document.getElementById(\"Rul_table_body\");\n"
                "    a.innerHTML=\"\";\n"
                "    for (d in data.rul)\n"
                "        if (data.rul.hasOwnProperty(d)) {\n"
                "            b = document.createElement(\"tr\"), b.id = data.rul[d][1], b.className = \"rul_row\", b.onclick = function () {\n"
                "                changeRowRul(this.id)\n"
                "            };\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = data.rul[d][0],\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = data.rul[d][1],\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rul[d][2]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rul[d][3]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rul[d][4]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = humanize_time(data.rul[d][5]),\n"
                "                b.appendChild(c);\n"
                "            c = document.createElement(\"td\"),\n"
                "                c.innerHTML = minify_numbers(data.rul[d][6]),\n"
                "                b.appendChild(c);\n"
                "\n"
                "            c = document.createElement(\"td\"),\n"
                "                div = document.createElement(\"div\"),\n"
                "                div.className = \"perc_time\",\n"
                "                div.style.width = data.rul[d][2] / f * 100 + \"%\",\n"
                "                div.innerHTML = clean_percentages(data.rul[d][2] / f * 100),\n"
                "                c.appendChild(div),\n"
                "                b.appendChild(c),\n"
                "                c = document.createElement(\"td\"),\n"
                "                div = document.createElement(\"div\"),\n"
                "                div.className = \"perc_time\",\n"
                "                div.style.width = 100 * parseFloat(data.rul[d][6]) / g + \"%\",\n"
                "                div.innerHTML = clean_percentages(100 * parseFloat(data.rul[d][6]) / g),\n"
                "                c.appendChild(div),\n"
                "                b.appendChild(c),\n"
                "                c = document.createElement(\"td\"),\n"
                "                c.innerHTML = data.rul[d][7],\n"
                "                b.appendChild(c),\n"
                "                a.appendChild(b)\n"
                "        }\n"
                "}\n"
                "\n"
                "function init() {\n"
                "    gen_top();\n"
                "    gen_rel_table();\n"
                "    gen_rul_table();\n"
                "    document.getElementById(\"default\").click();\n"
                "    new Tablesort(document.getElementById(\"Rel_table\"));\n"
                "    new Tablesort(document.getElementById(\"Rul_table\"));\n"
                "}\n"
                "\n"
                "function toggle_precision() {\n"
                "    precision=!precision;\n"
                "    gen_rel_table();\n"
                "    gen_rul_table();\n"
                "    if (selected) {\n"
                "        if (selected.rul) {\n"
                "            changeRowRul(selected.rul);\n"
                "        }\n"
                "        if (selected.rel) {\n"
                "            changeRowRel(selected.rel);\n"
                "        }\n"
                "    }\n"
                "}\n"
                "\n"
                "\n"
                "var created_relrul = !1,\n"
                "    created_rulver = !1,\n"
                "    selected_for_chart = !1,\n"
                "    show_graph_vals = !1,\n"
                "    precision = !1,\n"
                "    selected = {rel:!1,rul:!1};\n"
                "init();</script></html>";
    }
};